#!/bin/bash
# Tier-1 harness for qemu-ad-pve.sh. Stubs only: no root, no dpkg, no PVE, no VM.
# Usage: qemu-ad-pve-tier1.sh /path/to/qemu-ad-pve.sh
# Everything happens in a mktemp dir. rm is shadowed by a no-op function for purge tests.
set -u
SCRIPT=$(readlink -f "${1:?path to qemu-ad-pve.sh}")
W=$(mktemp -d /tmp/qad-t1.XXXXXX); trap 'command rm -rf "$W"' EXIT
pass=0; fail=0; info=0
ok()   { printf 'PASS  %s\n' "$1"; pass=$((pass+1)); }
bad()  { printf 'FAIL  %s\n' "$1"; fail=$((fail+1)); }
note() { printf 'INFO  %s\n' "$1"; info=$((info+1)); }
chk()  { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

# library = script minus the final "main" call
grep -q '^main "\$@"$' "$SCRIPT" || { echo "unexpected script tail"; exit 2; }
sed '$d' "$SCRIPT" > "$W/lib.sh"

# stub dpkg-divert modelled on the real one: --rename refuses to overwrite.
mkdir -p "$W/stub"
cat > "$W/stub/dpkg-divert" <<'S'
#!/bin/bash
st=$STATE/div; mode=list; ren=0; div=""; args=("$@"); path="${args[-1]}"
for ((i=0;i<${#args[@]}-1;i++)); do case ${args[i]} in
  --list) mode=list;; --remove) mode=remove;; --rename) ren=1;; --local) ;;
  --divert) div=${args[i+1]};; esac; done
[[ $* == *--list* ]] && mode=list || { [[ $mode == list ]] && mode=add; }
echo "$*" >> "$STATE/calls"
case $mode in
 list) [[ -f $st ]] && grep -F -- "$path" "$st" | awk -F'|' '{print "local diversion of "$1" to "$2}';;
 add) [[ -e $div ]] && { echo "dpkg-divert: error: rename involves overwriting" >&2; exit 2; }
      ((ren)) && mv "$path" "$div"; echo "$path|$div" > "$st";;
 remove) [[ -n ${FAIL_REMOVE:-} ]] && { echo "dpkg: error: dpkg frontend lock held" >&2; exit 2; }
      d=$(cut -d'|' -f2 "$st"); [[ -e $path ]] && { echo "dpkg-divert: error: rename involves overwriting $path" >&2; exit 2; }
      ((ren)) && mv "$d" "$path"; rm -f "$st";;
esac
S
chmod +x "$W/stub/dpkg-divert"
cat > "$W/real" <<'S'
#!/bin/bash
printf 'REAL'; printf ' [%s]' "$@"; echo
S
cat > "$W/side" <<'S'
#!/bin/bash
printf 'SIDE'; printf ' [%s]' "$@"; echo
S
chmod +x "$W/real" "$W/side"

# fresh scratch "host": /usr/bin/kvm == vendor
fresh() { T=$W/h; command rm -rf "$T"; mkdir -p "$T"; export STATE=$T; printf 'vendor\n' > "$T/kvm"; chmod +x "$T/kvm"; : > "$T/calls"; }
L() { # run snippet with lib sourced + paths set, strict mode like the real script
  PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail
    WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' SIDE_BIN='$W/side' LIST_FILE='$T/vms' LOG_FILE='$T/log' PREFIX=\${PREFIX:-/opt/qemu-ad}
    $1"; }
kvm_intact() { [[ -f $T/kvm ]] && [[ -x $T/kvm ]]; }

echo "== C1 install atomicity"
fresh; L 'write_wrapper(){ echo "injected write failure" >&2; return 1; }; install_wrapper' >/dev/null 2>&1; rc=$?
chk "C1a injected write failure: rc!=0"                    '[[ $rc -ne 0 ]]'
chk "C1a /usr/bin/kvm still the vendor file"               'kvm_intact && grep -qx vendor "$T/kvm"'
chk "C1a no divert was created"                            '! grep -q -- --rename "$T/calls"'
fresh; ln -s /dev/full "$T/kvm.qemu-ad-new"; L 'install_wrapper' >/dev/null 2>&1; rc=$?   # ENOSPC on staged file
chk "C1b ENOSPC on staged wrapper: rc!=0 and kvm intact"   '[[ $rc -ne 0 ]] && kvm_intact && grep -qx vendor "$T/kvm" && ! grep -q -- --rename "$T/calls"'
fresh; L 'write_wrapper(){ printf "if then\n" > "$1"; }; install_wrapper' >/dev/null 2>&1; rc=$?
chk "C1c wrapper failing bash -n: rc!=0, kvm intact, no divert" '[[ $rc -ne 0 ]] && kvm_intact && grep -qx vendor "$T/kvm" && ! grep -q -- --rename "$T/calls"'
fresh; L 'install_wrapper' >/dev/null 2>&1
chk "C1d good install: kvm is wrapper, kvm.pve is vendor"  'grep -q "Generated by qemu-ad-pve" "$T/kvm" && grep -qx vendor "$T/kvm.pve"'
cp "$T/kvm" "$W/w1"; L 'install_wrapper' >/dev/null 2>&1
chk "C1e reinstall idempotent (wrapper identical, vendor untouched)" 'cmp -s "$T/kvm" "$W/w1" && grep -qx vendor "$T/kvm.pve" && [[ $(grep -c -- --rename "$T/calls") -eq 1 ]]'
chk "C1f no staged leftovers after good install"            '[[ ! -e $T/kvm.qemu-ad-new ]]'
fresh; L 'install_wrapper' >/dev/null 2>&1; fresh2=1
fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' SIDE_BIN='$W/side' LIST_FILE='$T/vms' LOG_FILE='$T/log'
   mv(){ if [[ \${*: -1} == '$T/kvm' ]]; then return 1; fi; command mv \"\$@\"; }; install_wrapper" >/dev/null 2>&1
if [[ -e $T/kvm ]]; then ok "C1g (info) failed final mv: kvm present"; else note "C1g KNOWN RESIDUAL GAP: final mv fails after divert -> /usr/bin/kvm missing (no rollback)"; fi
fresh; L 'write_wrapper(){ return 1; }; install_wrapper' >/dev/null 2>&1; [[ -e $T/kvm.qemu-ad-new ]] && note "C1h staged file left behind after abort (cosmetic)" || ok "C1h no staged leftover after abort"

echo "== C2 uninstall order / dpkg failure"
fresh; L 'install_wrapper' >/dev/null 2>&1
FAIL_REMOVE=1 L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2a divert-remove failure: rc!=0"                      '[[ $rc -ne 0 ]]'
chk "C2a kvm still present AND is the wrapper"              'kvm_intact && grep -q "Generated by qemu-ad-pve" "$T/kvm"'
chk "C2a kvm.pve still present (divert untouched)"          '[[ -e $T/kvm.pve ]]'
chk "C2a no .qemu-ad-removed leftover"                      '[[ ! -e $T/kvm.qemu-ad-removed ]]'
L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2b clean uninstall: rc==0, kvm is vendor again"       '[[ $rc -eq 0 ]] && grep -qx vendor "$T/kvm" && [[ ! -e $T/kvm.pve ]] && [[ ! -e $T/kvm.qemu-ad-removed ]]'
L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2c uninstall twice: rc==0, kvm still vendor"          '[[ $rc -eq 0 ]] && grep -qx vendor "$T/kvm"'
fresh; L 'install_wrapper' >/dev/null 2>&1; command rm -f "$T/kvm"
FAIL_REMOVE=1 L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2d wrapper already missing + remove failure: no crash beyond rc!=0" '[[ $rc -ne 0 ]]'

# wrapper under test
mkw() { fresh; L 'write_wrapper "$WRAPPER_PATH"' >/dev/null; printf '200\n' > "$T/vms"; sed -i "s#^real=.*#real=$W/real#;s#^side=.*#side=$W/side#" "$T/kvm"; }
K() { "$T/kvm" "$@"; }
mkw
echo "== C3 -id handling"
o=$(K -id 200 -name vm -pidfile /var/run/qemu-server/200.pid -daemonize)
chk "C3a listed (pidfile): goes to SIDE, -id pair removed"  '[[ $o == "SIDE [-name] [vm] [-pidfile] [/var/run/qemu-server/200.pid] [-daemonize]" ]]'
o=$(K -id 200 -chardev 'socket,id=qmp,path=/var/run/qemu-server/200.qmp,server=on,wait=off')
chk "C3b listed (qmp chardev path only)"                    '[[ $o == "SIDE [-chardev] [socket,id=qmp,path=/var/run/qemu-server/200.qmp,server=on,wait=off]" ]]'
o=$(K -id 201 -pidfile /var/run/qemu-server/201.pid)
chk "C3c unlisted: REAL with -id intact"                    '[[ $o == "REAL [-id] [201] [-pidfile] [/var/run/qemu-server/201.pid]" ]]'
o=$(K -pidfile /var/run/qemu-server/2000.pid)
chk "C3d VMID 2000 must not match listed 200"               '[[ $o == REAL* ]]'
o=$(K -chardev 'socket,id=qmp,path=/var/run/qemu-server/-1.qmp,server=on' -pidfile /var/run/qemu-server/-1.pid)
chk "C3e qemu-server probe launch (fake vmid -1) -> REAL"   '[[ $o == REAL* ]]'
o=$(K -pidfile /var/run/qemu-server/200.pid -name -id -x)
note "C3f arg literally named -id as a VALUE is dropped on side path: $o"

echo "== C4 non-listed pass-through"
args=(-id 201 -name 'a b' -machine 'type=pc-q35-10.1+pve1,accel=kvm' -smbios $'type=1,product=x\ny' '' -drive 'file=/m/a+pve1/d' -pidfile /var/run/qemu-server/201.pid)
exp=$("$W/real" "${args[@]}"; echo x); got=$(K "${args[@]}"; echo x)
chk "C4a argv byte-identical to vendor (spaces, newline, empty, +pve)" '[[ "$got" == "$exp" ]]'
chk "C4b --version and -h routed to vendor"                 '[[ $(K --version) == "REAL [--version]" ]]'
rm -f "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
chk "C4c no list file: everything to vendor"                '[[ $o == REAL* ]]'
printf '200\r\n' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
chk "C4d CRLF list entry does not match (falls back to vendor, safe)" '[[ $o == REAL* ]]'
printf '200\n' > "$T/vms"; command rm -f "$W/side.bak"; mv "$W/side" "$W/side.bak"
K -pidfile /var/run/qemu-server/200.pid >/dev/null 2>&1; rc=$?; mv "$W/side.bak" "$W/side"
chk "C4e listed + missing side binary: loud failure (rc!=0), unlisted unaffected" '[[ $rc -ne 0 && $(K -pidfile /var/run/qemu-server/201.pid) == REAL* ]]'

echo "== C5 --purge guard (rm is a no-op recorder)"
purge() { fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }
   PREFIX='$1' LIST_FILE='$T/vms' WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" >/dev/null 2>&1; echo $?; }
for p in / /usr /etc /opt /opt/ /usr/local /usr/local/ /srv /home/x relative/opt opt/x; do
  r=$(purge "$p"); chk "C5 reject PREFIX='$p' (rc!=0, nothing removed)" '[[ $r -ne 0 && ! -s $T/rm.log ]]'
done
for p in /opt/qemu-ad /usr/local/qemu-ad /srv/qad; do
  r=$(purge "$p"); chk "C5 allow PREFIX='$p'" '[[ $r -eq 0 && -s $T/rm.log ]]'
done
for p in /opt/../usr /opt/qemu-ad/../.. /usr/local/bin /usr/local/../../etc; do
  r=$(purge "$p"); if [[ $r -ne 0 && ! -s $T/rm.log ]]; then ok "C5 reject traversal/system dir PREFIX='$p'"; else bad "C5 GUARD BYPASS PREFIX='$p' would rm: $(cat "$T/rm.log" 2>/dev/null | head -1)"; fi
done
fresh; L 'install_wrapper' >/dev/null 2>&1; r=$(PREFIX=/usr L 'uninstall --purge' >/dev/null 2>&1; echo $?)
chk "C5x refused purge changes nothing (divert + wrapper still in place)" '[[ $r -ne 0 ]] && grep -q "Generated by qemu-ad-pve" "$T/kvm" && [[ -e $T/kvm.pve ]]'
fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }; PREFIX= LIST_FILE='$T/vms' WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; echo PREFIX=\$PREFIX >> '$T/rm.log'; uninstall --purge" >/dev/null 2>&1
note "C5 empty PREFIX= env var: $(head -2 "$T/rm.log" 2>/dev/null | tr '\n' ' ')"

echo "== C6 +pveN strip only on -machine/-M"
mkw; printf '200\n' > "$T/vms"; P='-pidfile /var/run/qemu-server/200.pid'
o=$(K -machine 'type=pc-q35-10.1+pve1,accel=kvm' $P); chk "C6a -machine type=...+pve1 stripped" '[[ $o == *"[type=pc-q35-10.1,accel=kvm]"* ]]'
o=$(K -machine pc-q35-10.1+pve12 $P);               chk "C6b -machine bare +pve12 stripped"       '[[ $o == *"[pc-q35-10.1]"* ]]'
o=$(K -M pc-q35-10.1+pve2 $P);                      chk "C6c -M stripped"                          '[[ $o == *"[pc-q35-10.1]"* ]]'
o=$(K -name 'x+pve5' -smbios 'type=1,product=a+pve7' -drive 'file=/m/a+pve1/d' $P)
chk "C6d +pve in name/smbios/path untouched" '[[ $o == *"[x+pve5]"* && $o == *"product=a+pve7"* && $o == *"/m/a+pve1/d"* ]]'
o=$(K -machine pc-q35-10.1+pve1 -machine 'type=pc-i440fx-9.0+pve3' $P); chk "C6e two -machine args both stripped" '[[ $o == *"[pc-q35-10.1]"* && $o == *"[type=pc-i440fx-9.0]"* ]]'
o=$(K -name -machine pc-q35-10.1+pve1 $P);          note "C6f edge: '-name -machine X+pve1' (value that looks like option): $o"

echo "== C7 (simulated) vendor upgrade"
fresh; L 'install_wrapper' >/dev/null 2>&1; printf 'vendor-NEW\n' > "$T/kvm.pve"   # what dpkg does: new vendor lands on kvm.pve
grep -q "Generated by qemu-ad-pve" "$T/kvm" && ok "C7a wrapper untouched by new vendor file" || bad "C7a"
sed -i "s#^real=.*#real=$W/real#" "$T/kvm"; printf '200\n' > "$T/vms"; o=$("$T/kvm" -pidfile /var/run/qemu-server/201.pid)
chk "C7b unlisted still routed to vendor path" '[[ $o == REAL* ]]'
note "C7 real dpkg upgrade behaviour needs tier 2"


echo "== C8 follow-up hardening (findings 7-13)"
# Skip cleanly on a script that predates these changes? No: these are expected to FAIL on old main.
# --- finding 7/8: pins + .part + temp extract (fetch_sources with stub wget/git/tar)
mkdir -p "$W/stub"
cat > "$W/stub/wget" <<'S'
#!/bin/bash
# usage: wget -O <out> <url>; behaviour driven by $WGET_MODE
out=""; while [[ $# -gt 0 ]]; do [[ $1 == -O ]] && { out=$2; shift; }; shift; done
case "${WGET_MODE:-ok}" in
  ok)   printf 'tarball-bytes\n' > "$out" ;;
  fail) printf 'partial' > "$out"; exit 4 ;;
esac
S
cat > "$W/stub/git" <<'S'
#!/bin/bash
# only used by fetch_sources: clone creates dir with a patch; pull is a no-op
case "$1" in
  clone) d="${@: -1}"; mkdir -p "$d/.git"; printf 'patch-bytes\n' > "$d/qemu-${QEMU_VER:-10.2.2}.patch" ;;
  *) : ;;
esac
S
cat > "$W/stub/tar" <<'S'
#!/bin/bash
# usage: tar -C <dir> -xJf <file>; TAR_MODE=ok|fail|badtop
d=""; while [[ $# -gt 0 ]]; do [[ $1 == -C ]] && { d=$2; shift; }; shift; done
case "${TAR_MODE:-ok}" in
  ok)     mkdir -p "$d/qemu-${QEMU_VER:-10.2.2}"; echo x > "$d/qemu-${QEMU_VER:-10.2.2}/configure" ;;
  fail)   mkdir -p "$d/qemu-${QEMU_VER:-10.2.2}"; echo half > "$d/qemu-${QEMU_VER:-10.2.2}/partial"; exit 2 ;;
  badtop) mkdir -p "$d/other" ;;
esac
S
chmod +x "$W/stub/wget" "$W/stub/git" "$W/stub/tar"
FS() { # FS <env assignments...> -- run fetch_sources in a fresh SRC_ROOT; sets R=$W/src
  command rm -rf "$W/src"; mkdir -p "$W/src"
  env "$@" PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SRC_ROOT='$W/src' PATCH_DIR='$W/src/qemu-anti-detection' SRC_DIR='$W/src/qemu-'\${QEMU_VER}; PATCH_FILE=\$PATCH_DIR/qemu-\${QEMU_VER}.patch; fetch_sources" >"$W/fs.out" 2>&1; }
H_T=$(printf 'tarball-bytes\n' | sha256sum | awk '{print $1}'); H_P=$(printf 'patch-bytes\n' | sha256sum | awk '{print $1}')
grep -q 'QEMU_SHA256' "$W/lib.sh" && has_pin=1 || has_pin=0
chk "C8a script defines default pins for 10.2.2" 'grep -q 784b296ff29c1417aa72323abcb2d2ea9ab9771724f577dcd785c3b04f21e176 "$W/lib.sh" && grep -q 0d05f1a0ced91cef3fe33203b7d81c955d64694f30085544dc5e154809da110e "$W/lib.sh"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P; rc=$?
chk "C8b matching pins: fetch ok, source dir present, no .part/.extract leftovers" '[[ $rc -eq 0 && -f $W/src/qemu-10.2.2/configure && ! -e $W/src/qemu-10.2.2.tar.xz.part && -z $(ls -A $W/src | grep "^\.extract") ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=deadbeef PATCH_SHA256=$H_P; rc=$?
chk "C8c wrong tarball SHA: fatal, no extract" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 ]] && grep -qi "mismatch" "$W/fs.out"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=deadbeef; rc=$?
chk "C8d wrong patch SHA: fatal before download" '[[ $rc -ne 0 && ! -e $W/src/qemu-10.2.2.tar.xz ]] && grep -qi "mismatch" "$W/fs.out"'
FS QEMU_VER=9.9.9 QEMU_SHA256= PATCH_SHA256=; rc=$?
chk "C8e unknown version, no pin: warns but proceeds" '[[ $rc -eq 0 ]] && grep -qi "no pinned" "$W/fs.out"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P WGET_MODE=fail; rc=$?
chk "C8f wget failure: fatal, no tarball and no .part left" '[[ $rc -ne 0 && ! -e $W/src/qemu-10.2.2.tar.xz && ! -e $W/src/qemu-10.2.2.tar.xz.part ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P TAR_MODE=fail; rc=$?
chk "C8g tar failure: fatal, no half-extracted source dir, no temp dir" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 && -z $(ls -A $W/src | grep "^\.extract") ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P TAR_MODE=badtop; rc=$?
chk "C8h tarball with unexpected top dir: fatal, nothing left" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 && -z $(ls -A $W/src | grep "^\.extract") ]]'
# a stale .part from an earlier interrupted run must not be trusted
command rm -rf "$W/src"; mkdir -p "$W/src"; printf 'junk' > "$W/src/qemu-10.2.2.tar.xz.part"
env QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SRC_ROOT='$W/src' PATCH_DIR='$W/src/qemu-anti-detection' SRC_DIR='$W/src/qemu-10.2.2'; PATCH_FILE=\$PATCH_DIR/qemu-10.2.2.patch; fetch_sources" >/dev/null 2>&1; rc=$?
chk "C8i stale .part replaced by a fresh download" '[[ $rc -eq 0 && $(cat $W/src/qemu-10.2.2.tar.xz) == tarball-bytes ]]'

# --- finding 10: apt-get update failure tolerated
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
echo "apt-get $*" >> "${STATE:-/tmp}/apt.log"; [[ $1 == update ]] && exit 100; exit 0
S
chmod +x "$W/stub/apt-get"; fresh; : > "$T/apt.log"
L 'install_deps' >/dev/null 2>"$W/apt.err"; rc=$?
chk "C8j apt-get update failure: warns, still runs apt-get install" '[[ $rc -eq 0 ]] && grep -q "apt-get install" "$T/apt.log" && grep -qi "update failed" "$W/apt.err"'
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
echo "apt-get $*" >> "${STATE:-/tmp}/apt.log"; [[ $1 == install ]] && exit 100; exit 0
S
fresh; : > "$T/apt.log"; L 'install_deps' >/dev/null 2>&1; rc=$?
chk "C8k apt-get install failure is still fatal" '[[ $rc -ne 0 ]]'

# --- finding 9: version skew warning
cat > "$W/side134" <<'S'
#!/bin/bash
echo "QEMU emulator version 9.1.0"
S
chmod +x "$W/side134"; fresh
o=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SIDE_BIN='$W/side134' QEMU_VER=10.2.2 WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' LIST_FILE='$T/vms' PREFIX=/opt/qemu-ad; warn_version_skew" 2>&1); rc=$?
chk "C8l skew (installed 9.1.0, want 10.2.2): warning, rc 0" '[[ $rc -eq 0 && $o == *"warning"* && $o == *"9.1.0"* ]]'
cat > "$W/side134" <<'S'
#!/bin/bash
echo "QEMU emulator version 10.2.2"
S
o=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SIDE_BIN='$W/side134' QEMU_VER=10.2.2; warn_version_skew" 2>&1)
chk "C8m no skew: silent" '[[ -z $o ]]'

# --- finding 11: del-vm
fresh; printf '200\n201\n202\n' > "$T/vms"; chmod 640 "$T/vms"
L 'del_vm 201' >/dev/null 2>&1; rc=$?
chk "C8n del-vm removes only that id" '[[ $rc -eq 0 ]] && [[ $(cat $T/vms | tr "\n" " ") == "200 202 " ]]'
chk "C8o del-vm preserves mode" '[[ $(stat -c %a $T/vms) == 640 ]]'
chk "C8p del-vm leaves no temp files next to the list" '[[ $(ls $T | grep -c "^vms\.") -eq 0 ]]'
fresh; printf '200\n' > "$T/vms"; L 'del_vm 200' >/dev/null 2>&1; rc=$?
chk "C8q del-vm of the last id: ok, empty list (grep exit 1 tolerated)" '[[ $rc -eq 0 && ! -s $T/vms ]]'
fresh; printf '200\n' > "$T/vms"
cat > "$W/stub/grep" <<'S'
#!/bin/bash
[[ $1 == -vx ]] && exit 2; exec /bin/grep "$@"
S
chmod +x "$W/stub/grep"; L 'del_vm 200' >/dev/null 2>&1; rc=$?
chk "C8r grep hard error: fatal, list unchanged, no temp left" '[[ $rc -ne 0 && $(cat $T/vms) == 200 && $(ls $T | grep -c "^vms\.") -eq 0 ]]'
command rm -f "$W/stub/grep"

# --- finding 13: leading-zero VMIDs, quoted wrapper paths
fresh; L 'add_vm 0200' >/dev/null 2>&1; rc=$?
chk "C8s add-vm rejects leading-zero VMID" '[[ $rc -ne 0 ]] && ! grep -qx 0200 "$T/vms" 2>/dev/null'
fresh; L 'del_vm 0200' >/dev/null 2>&1; rc=$?   # list absent -> must still fail
chk "C8t del-vm rejects leading-zero VMID" '[[ $rc -ne 0 ]]'
fresh; L 'add_vm 200' >/dev/null 2>&1; rc=$?
chk "C8u add-vm 200 still works" '[[ $rc -eq 0 ]] && grep -qx 200 "$T/vms"'
# wrapper with a space and $ in paths must still be valid and route correctly
fresh; mkdir -p "$T/we ird"; cp "$W/real" "$T/we ird/re al"; cp "$W/side" "$T/we ird/si de"
PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; VENDOR_PATH='$T/we ird/re al' SIDE_BIN='$T/we ird/si de' LIST_FILE='$T/we ird/vm s' LOG_FILE='$T/we ird/log'; write_wrapper '$T/wr'" >/dev/null 2>&1
printf '200\n' > "$T/we ird/vm s"
chk "C8v wrapper with spaces in paths passes bash -n" 'bash -n "$T/wr"'
o=$(bash "$T/wr" -pidfile /var/run/qemu-server/200.pid); chk "C8w spaced paths: listed id -> side" '[[ $o == SIDE* ]]'
o=$(bash "$T/wr" -pidfile /var/run/qemu-server/201.pid); chk "C8x spaced paths: unlisted id -> vendor" '[[ $o == REAL* ]]'
fresh; mkdir -p "$T/d"; cp "$W/side" "$T/d/"'s$(touch PWNED)'
PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; VENDOR_PATH='$W/real' SIDE_BIN='$T/d/s\$(touch PWNED)' LIST_FILE='$T/vms' LOG_FILE='$T/log'; write_wrapper '$T/wr2'" >/dev/null 2>&1
printf '200\n' > "$T/vms"; ( cd "$T" && bash "$T/wr2" -pidfile /var/run/qemu-server/200.pid >"$T/wr2.out" 2>&1 )
chk "C8y metacharacters in SIDE_BIN are not executed; wrapper still reaches the side binary" '[[ ! -e $T/PWNED && $(cat $T/wr2.out) == SIDE* ]]'

echo; echo "TIER1 RESULT: pass=$pass fail=$fail info=$info  (script: $SCRIPT)"
[[ $fail -eq 0 ]]
