#!/bin/bash
# Tier-1 harness for qemu-ad-pve.sh. Stubs only: no root, no dpkg, no PVE, no VM.
# Usage: qemu-ad-pve-tier1.sh /path/to/qemu-ad-pve.sh
# Everything happens in a mktemp dir. rm is shadowed by a no-op function for purge tests.
set -u
SCRIPT=$(readlink -f "${1:?path to qemu-ad-pve.sh}")
W=$(mktemp -d /tmp/qad-t1.XXXXXX); trap 'command rm -rf "$W"' EXIT
pass=0; fail=0; info=0
ok()   { printf 'PASS  %s\n' "$1"; pass=$((pass+1)); }
bad()  { printf 'FAIL  %s\n' "$1"; fail=$((fail+1)); }
note() { printf 'INFO  %s\n' "$1"; info=$((info+1)); }
chk()  { if eval "$2"; then ok "$1"; else bad "$1"; fi; }

# library = script minus the final "main" call
grep -q '^main "\$@"$' "$SCRIPT" || { echo "unexpected script tail"; exit 2; }
sed '$d' "$SCRIPT" > "$W/lib.sh"

# stub dpkg-divert modelled on the real one: --rename refuses to overwrite.
mkdir -p "$W/stub"
cat > "$W/stub/dpkg-divert" <<'S'
#!/bin/bash
st=$STATE/div; mode=list; ren=0; div=""; args=("$@"); path="${args[-1]}"
for ((i=0;i<${#args[@]}-1;i++)); do case ${args[i]} in
  --list) mode=list;; --remove) mode=remove;; --rename) ren=1;; --no-rename) ;; --local) ;;
  --divert) div=${args[i+1]};; esac; done
[[ $* == *--list* ]] && mode=list || { [[ $mode == list ]] && mode=add; }
echo "$*" >> "$STATE/calls"
case $mode in
 list) [[ -f $st ]] && grep -F -- "$path" "$st" | awk -F'|' '{print "local diversion of "$1" to "$2}';;
 add) ((ren)) && [[ -e $div ]] && { echo "dpkg-divert: error: rename involves overwriting" >&2; exit 2; }
      ((ren)) && mv "$path" "$div"; echo "$path|$div" > "$st";;
 remove) [[ -n ${FAIL_REMOVE:-} ]] && { echo "dpkg: error: dpkg frontend lock held" >&2; exit 2; }
      d=$(cut -d'|' -f2 "$st"); ((ren)) && [[ -e $path ]] && { echo "dpkg-divert: error: rename involves overwriting $path" >&2; exit 2; }
      ((ren)) && mv "$d" "$path"; rm -f "$st";;
esac
S
chmod +x "$W/stub/dpkg-divert"
cat > "$W/real" <<'S'
#!/bin/bash
printf 'REAL'; printf ' [%s]' "$@"; echo
S
cat > "$W/side" <<'S'
#!/bin/bash
printf 'SIDE'; printf ' [%s]' "$@"; echo
S
chmod +x "$W/real" "$W/side"

# fresh scratch "host": /usr/bin/kvm == vendor
fresh() { T=$W/h; command rm -rf "$T"; mkdir -p "$T"; export STATE=$T; printf 'vendor\n' > "$T/kvm"; chmod +x "$T/kvm"; : > "$T/calls"; }
L() { # run snippet with lib sourced + paths set, strict mode like the real script
  PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail
    WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' SIDE_BIN='$W/side' LIST_FILE='$T/vms' LOG_FILE='$T/log' PREFIX=\${PREFIX:-/opt/qemu-ad}
    $1"; }
kvm_intact() { [[ -f $T/kvm ]] && [[ -x $T/kvm ]]; }

echo "== C1 install atomicity"
fresh; L 'write_wrapper(){ echo "injected write failure" >&2; return 1; }; install_wrapper' >/dev/null 2>&1; rc=$?
chk "C1a injected write failure: rc!=0"                    '[[ $rc -ne 0 ]]'
chk "C1a /usr/bin/kvm still the vendor file"               'kvm_intact && grep -qx vendor "$T/kvm"'
chk "C1a no divert was created"                            '! grep -q -- --divert "$T/calls"'
fresh; ln -s /dev/full "$T/kvm.qemu-ad-new"; L 'install_wrapper' >/dev/null 2>&1; rc=$?   # ENOSPC on staged file
chk "C1b ENOSPC on staged wrapper: rc!=0 and kvm intact"   '[[ $rc -ne 0 ]] && kvm_intact && grep -qx vendor "$T/kvm" && ! grep -q -- --divert "$T/calls"'
fresh; L 'write_wrapper(){ printf "if then\n" > "$1"; }; install_wrapper' >/dev/null 2>&1; rc=$?
chk "C1c wrapper failing bash -n: rc!=0, kvm intact, no divert" '[[ $rc -ne 0 ]] && kvm_intact && grep -qx vendor "$T/kvm" && ! grep -q -- --divert "$T/calls"'
fresh; L 'install_wrapper' >/dev/null 2>&1
chk "C1d good install: kvm is wrapper, kvm.pve is vendor"  'grep -q "Generated by qemu-ad-pve" "$T/kvm" && grep -qx vendor "$T/kvm.pve"'
cp "$T/kvm" "$W/w1"; L 'install_wrapper' >/dev/null 2>&1
chk "C1e reinstall idempotent (wrapper identical, vendor untouched)" 'cmp -s "$T/kvm" "$W/w1" && grep -qx vendor "$T/kvm.pve" && [[ $(grep -c -- --divert "$T/calls") -eq 1 ]]'
chk "C1f no staged leftovers after good install"            '[[ ! -e $T/kvm.qemu-ad-new ]]'
fresh; L 'install_wrapper' >/dev/null 2>&1; fresh2=1
fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' SIDE_BIN='$W/side' LIST_FILE='$T/vms' LOG_FILE='$T/log'
   mv(){ if [[ \${*: -1} == '$T/kvm' ]]; then return 1; fi; command mv \"\$@\"; }; install_wrapper" >/dev/null 2>&1
if [[ -e $T/kvm ]]; then ok "C1g (info) failed final mv: kvm present"; else note "C1g KNOWN RESIDUAL GAP: final mv fails after divert -> /usr/bin/kvm missing (no rollback)"; fi
fresh; L 'write_wrapper(){ return 1; }; install_wrapper' >/dev/null 2>&1; [[ -e $T/kvm.qemu-ad-new ]] && note "C1h staged file left behind after abort (cosmetic)" || ok "C1h no staged leftover after abort"

echo "== C2 uninstall order / dpkg failure"
fresh; L 'install_wrapper' >/dev/null 2>&1
FAIL_REMOVE=1 L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2a divert-remove failure: rc!=0"                      '[[ $rc -ne 0 ]]'
chk "C2a kvm still present AND is the wrapper"              'kvm_intact && grep -q "Generated by qemu-ad-pve" "$T/kvm"'
chk "C2a kvm.pve still present (divert untouched)"          '[[ -e $T/kvm.pve ]]'
chk "C2a no .qemu-ad-removed leftover"                      '[[ ! -e $T/kvm.qemu-ad-removed ]]'
L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2b clean uninstall: rc==0, kvm is vendor again"       '[[ $rc -eq 0 ]] && grep -qx vendor "$T/kvm" && [[ ! -e $T/kvm.pve ]] && [[ ! -e $T/kvm.qemu-ad-removed ]]'
L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2c uninstall twice: rc==0, kvm still vendor"          '[[ $rc -eq 0 ]] && grep -qx vendor "$T/kvm"'
fresh; L 'install_wrapper' >/dev/null 2>&1; command rm -f "$T/kvm"
FAIL_REMOVE=1 L 'uninstall' >/dev/null 2>&1; rc=$?
chk "C2d wrapper already missing + remove failure: no crash beyond rc!=0" '[[ $rc -ne 0 ]]'

# wrapper under test
mkw() { fresh; L 'write_wrapper "$WRAPPER_PATH"' >/dev/null; printf '200\n' > "$T/vms"; sed -i "s#^real=.*#real=$W/real#;s#^side=.*#side=$W/side#" "$T/kvm"; }
K() { "$T/kvm" "$@"; }
mkw
echo "== C3 -id handling"
o=$(K -id 200 -name vm -pidfile /var/run/qemu-server/200.pid -daemonize)
chk "C3a listed (pidfile): goes to SIDE, -id pair removed"  '[[ $o == "SIDE [-name] [vm] [-pidfile] [/var/run/qemu-server/200.pid] [-daemonize]" ]]'
o=$(K -id 200 -chardev 'socket,id=qmp,path=/var/run/qemu-server/200.qmp,server=on,wait=off')
chk "C3b listed (qmp chardev path only)"                    '[[ $o == "SIDE [-chardev] [socket,id=qmp,path=/var/run/qemu-server/200.qmp,server=on,wait=off]" ]]'
o=$(K -id 201 -pidfile /var/run/qemu-server/201.pid)
chk "C3c unlisted: REAL with -id intact"                    '[[ $o == "REAL [-id] [201] [-pidfile] [/var/run/qemu-server/201.pid]" ]]'
o=$(K -pidfile /var/run/qemu-server/2000.pid)
chk "C3d VMID 2000 must not match listed 200"               '[[ $o == REAL* ]]'
o=$(K -chardev 'socket,id=qmp,path=/var/run/qemu-server/-1.qmp,server=on' -pidfile /var/run/qemu-server/-1.pid)
chk "C3e qemu-server probe launch (fake vmid -1) -> REAL"   '[[ $o == REAL* ]]'
o=$(K -pidfile /var/run/qemu-server/200.pid -name -id -x)
note "C3f arg literally named -id as a VALUE is dropped on side path: $o"

echo "== C4 non-listed pass-through"
args=(-id 201 -name 'a b' -machine 'type=pc-q35-10.1+pve1,accel=kvm' -smbios $'type=1,product=x\ny' '' -drive 'file=/m/a+pve1/d' -pidfile /var/run/qemu-server/201.pid)
exp=$("$W/real" "${args[@]}"; echo x); got=$(K "${args[@]}"; echo x)
chk "C4a argv byte-identical to vendor (spaces, newline, empty, +pve)" '[[ "$got" == "$exp" ]]'
chk "C4b --version and -h routed to vendor"                 '[[ $(K --version) == "REAL [--version]" ]]'
rm -f "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
chk "C4c no list file: everything to vendor"                '[[ $o == REAL* ]]'
printf '200\r\n' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
chk "C4d CRLF list entry '200\\r' now matches (N3: routes to side)" '[[ $o == SIDE* ]]'
printf '200\n' > "$T/vms"; command rm -f "$W/side.bak"; mv "$W/side" "$W/side.bak"
K -pidfile /var/run/qemu-server/200.pid >/dev/null 2>&1; rc=$?; mv "$W/side.bak" "$W/side"
chk "C4e listed + missing side binary: loud failure (rc!=0), unlisted unaffected" '[[ $rc -ne 0 && $(K -pidfile /var/run/qemu-server/201.pid) == REAL* ]]'

echo "== C5 --purge guard (rm is a no-op recorder)"
purge() { fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }
   PREFIX='$1' LIST_FILE=\${PURGE_LIST:-/etc/qemu-ad/vms} WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" >/dev/null 2>&1; echo $?; }
for p in / /usr /etc /opt /opt/ /usr/local /usr/local/ /srv /home/x relative/opt opt/x; do
  r=$(purge "$p"); chk "C5 reject PREFIX='$p' (rc!=0, nothing removed)" '[[ $r -ne 0 && ! -s $T/rm.log ]]'
done
for p in /opt/qemu-ad /usr/local/qemu-ad /srv/qad; do
  r=$(purge "$p"); chk "C5 allow PREFIX='$p'" '[[ $r -eq 0 && -s $T/rm.log ]]'
done
for p in /opt/../usr /opt/qemu-ad/../.. /usr/local/bin /usr/local/../../etc /usr/local/./bin /usr/local/./share /opt/. /opt/./x /opt/qemu-ad/. /opt/qemu-ad/./ /usr/local/bin/. /./opt/x /opt/qemu-ad/.. /usr/local/sbin /srv/. /srv/./qad; do
  r=$(purge "$p"); if [[ $r -ne 0 && ! -s $T/rm.log ]]; then ok "C5 reject traversal/system dir PREFIX='$p'"; else bad "C5 GUARD BYPASS PREFIX='$p' would rm: $(cat "$T/rm.log" 2>/dev/null | head -1)"; fi
done
fresh; L 'install_wrapper' >/dev/null 2>&1; r=$(PREFIX=/usr L 'uninstall --purge' >/dev/null 2>&1; echo $?)
chk "C5x refused purge changes nothing (divert + wrapper still in place)" '[[ $r -ne 0 ]] && grep -q "Generated by qemu-ad-pve" "$T/kvm" && [[ -e $T/kvm.pve ]]'
fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }; PREFIX= LIST_FILE='$T/vms' WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; echo PREFIX=\$PREFIX >> '$T/rm.log'; uninstall --purge" >/dev/null 2>&1
chk "C5 empty PREFIX= is rejected before any rm (artifact fixed: runs through the same guard, rm recorder empty)" '[[ ! -s $T/rm.log || $(grep -c "^RM" $T/rm.log) -eq 0 ]]'

echo "== C6 +pveN strip only on -machine/-M"
mkw; printf '200\n' > "$T/vms"; P='-pidfile /var/run/qemu-server/200.pid'
o=$(K -machine 'type=pc-q35-10.1+pve1,accel=kvm' $P); chk "C6a -machine type=...+pve1 stripped" '[[ $o == *"[type=pc-q35-10.1,accel=kvm]"* ]]'
o=$(K -machine pc-q35-10.1+pve12 $P);               chk "C6b -machine bare +pve12 stripped"       '[[ $o == *"[pc-q35-10.1]"* ]]'
o=$(K -M pc-q35-10.1+pve2 $P);                      chk "C6c -M stripped"                          '[[ $o == *"[pc-q35-10.1]"* ]]'
o=$(K -name 'x+pve5' -smbios 'type=1,product=a+pve7' -drive 'file=/m/a+pve1/d' $P)
chk "C6d +pve in name/smbios/path untouched" '[[ $o == *"[x+pve5]"* && $o == *"product=a+pve7"* && $o == *"/m/a+pve1/d"* ]]'
o=$(K -machine pc-q35-10.1+pve1 -machine 'type=pc-i440fx-9.0+pve3' $P); chk "C6e two -machine args both stripped" '[[ $o == *"[pc-q35-10.1]"* && $o == *"[type=pc-i440fx-9.0]"* ]]'
o=$(K -name -machine pc-q35-10.1+pve1 $P);          note "C6f edge: '-name -machine X+pve1' (value that looks like option): $o"

echo "== C7 (simulated) vendor upgrade"
fresh; L 'install_wrapper' >/dev/null 2>&1; printf 'vendor-NEW\n' > "$T/kvm.pve"   # what dpkg does: new vendor lands on kvm.pve
grep -q "Generated by qemu-ad-pve" "$T/kvm" && ok "C7a wrapper untouched by new vendor file" || bad "C7a"
sed -i "s#^real=.*#real=$W/real#" "$T/kvm"; printf '200\n' > "$T/vms"; o=$("$T/kvm" -pidfile /var/run/qemu-server/201.pid)
chk "C7b unlisted still routed to vendor path" '[[ $o == REAL* ]]'
note "C7 real dpkg upgrade behaviour needs tier 2"


echo "== C8 follow-up hardening (findings 7-13)"
# Skip cleanly on a script that predates these changes? No: these are expected to FAIL on old main.
# --- finding 7/8: pins + .part + temp extract (fetch_sources with stub wget/git/tar)
mkdir -p "$W/stub"
cat > "$W/stub/wget" <<'S'
#!/bin/bash
# usage: wget -O <out> <url>; behaviour driven by $WGET_MODE
out=""; while [[ $# -gt 0 ]]; do [[ $1 == -O ]] && { out=$2; shift; }; shift; done
case "${WGET_MODE:-ok}" in
  ok)   printf 'tarball-bytes\n' > "$out" ;;
  fail) printf 'partial' > "$out"; exit 4 ;;
esac
S
cat > "$W/stub/git" <<'S'
#!/bin/bash
# only used by fetch_sources: clone creates dir with a patch; pull is a no-op
case "$1" in
  clone) d="${@: -1}"; mkdir -p "$d/.git"; printf 'patch-bytes\n' > "$d/qemu-${QEMU_VER:-10.2.2}.patch" ;;
  *) : ;;
esac
S
cat > "$W/stub/tar" <<'S'
#!/bin/bash
# usage: tar -C <dir> -xJf <file>; TAR_MODE=ok|fail|badtop
d=""; while [[ $# -gt 0 ]]; do [[ $1 == -C ]] && { d=$2; shift; }; shift; done
case "${TAR_MODE:-ok}" in
  ok)     mkdir -p "$d/qemu-${QEMU_VER:-10.2.2}"; echo x > "$d/qemu-${QEMU_VER:-10.2.2}/configure" ;;
  fail)   mkdir -p "$d/qemu-${QEMU_VER:-10.2.2}"; echo half > "$d/qemu-${QEMU_VER:-10.2.2}/partial"; exit 2 ;;
  badtop) mkdir -p "$d/other" ;;
esac
S
chmod +x "$W/stub/wget" "$W/stub/git" "$W/stub/tar"
FS() { # FS <env assignments...> -- run fetch_sources in a fresh SRC_ROOT; sets R=$W/src
  command rm -rf "$W/src"; mkdir -p "$W/src"
  env "$@" PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SRC_ROOT='$W/src' PATCH_DIR='$W/src/qemu-anti-detection' SRC_DIR='$W/src/qemu-'\${QEMU_VER}; PATCH_FILE=\$PATCH_DIR/qemu-\${QEMU_VER}.patch; fetch_sources" >"$W/fs.out" 2>&1; }
H_T=$(printf 'tarball-bytes\n' | sha256sum | awk '{print $1}'); H_P=$(printf 'patch-bytes\n' | sha256sum | awk '{print $1}')
grep -q 'QEMU_SHA256' "$W/lib.sh" && has_pin=1 || has_pin=0
chk "C8a script defines default pins for 10.2.2" 'grep -q 784b296ff29c1417aa72323abcb2d2ea9ab9771724f577dcd785c3b04f21e176 "$W/lib.sh" && grep -q 0d05f1a0ced91cef3fe33203b7d81c955d64694f30085544dc5e154809da110e "$W/lib.sh"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P; rc=$?
chk "C8b matching pins: fetch ok, source dir present, no .part/.extract leftovers" '[[ $rc -eq 0 && -f $W/src/qemu-10.2.2/configure && ! -e $W/src/qemu-10.2.2.tar.xz.part && -z $(ls -A $W/src | grep "^\.extract") ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=deadbeef PATCH_SHA256=$H_P; rc=$?
chk "C8c wrong tarball SHA: fatal, no extract" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 ]] && grep -qi "mismatch" "$W/fs.out"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=deadbeef; rc=$?
chk "C8d wrong patch SHA: fatal before download" '[[ $rc -ne 0 && ! -e $W/src/qemu-10.2.2.tar.xz ]] && grep -qi "mismatch" "$W/fs.out"'
FS QEMU_VER=9.9.9 QEMU_SHA256= PATCH_SHA256=; rc=$?
chk "C8e unknown version, no pin: warns but proceeds" '[[ $rc -eq 0 ]] && grep -qi "no pinned" "$W/fs.out"'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P WGET_MODE=fail; rc=$?
chk "C8f wget failure: fatal, no tarball and no .part left" '[[ $rc -ne 0 && ! -e $W/src/qemu-10.2.2.tar.xz && ! -e $W/src/qemu-10.2.2.tar.xz.part ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P TAR_MODE=fail; rc=$?
chk "C8g tar failure: fatal, no half-extracted source dir, no temp dir" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 && -z $(ls -A $W/src | grep "^\.extract") ]]'
FS QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P TAR_MODE=badtop; rc=$?
chk "C8h tarball with unexpected top dir: fatal, nothing left" '[[ $rc -ne 0 && ! -d $W/src/qemu-10.2.2 && -z $(ls -A $W/src | grep "^\.extract") ]]'
# a stale .part from an earlier interrupted run must not be trusted
command rm -rf "$W/src"; mkdir -p "$W/src"; printf 'junk' > "$W/src/qemu-10.2.2.tar.xz.part"
env QEMU_VER=10.2.2 QEMU_SHA256=$H_T PATCH_SHA256=$H_P PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SRC_ROOT='$W/src' PATCH_DIR='$W/src/qemu-anti-detection' SRC_DIR='$W/src/qemu-10.2.2'; PATCH_FILE=\$PATCH_DIR/qemu-10.2.2.patch; fetch_sources" >/dev/null 2>&1; rc=$?
chk "C8i stale .part replaced by a fresh download" '[[ $rc -eq 0 && $(cat $W/src/qemu-10.2.2.tar.xz) == tarball-bytes ]]'

# --- finding 10: apt-get update failure tolerated
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
echo "apt-get $*" >> "${STATE:-/tmp}/apt.log"; [[ $1 == update ]] && exit 100; exit 0
S
chmod +x "$W/stub/apt-get"; fresh; : > "$T/apt.log"
L 'install_deps' >/dev/null 2>"$W/apt.err"; rc=$?
chk "C8j apt-get update failure: warns, still runs apt-get install" '[[ $rc -eq 0 ]] && grep -q "apt-get install" "$T/apt.log" && grep -qi "update failed" "$W/apt.err"'
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
echo "apt-get $*" >> "${STATE:-/tmp}/apt.log"; [[ $1 == install ]] && exit 100; exit 0
S
fresh; : > "$T/apt.log"; L 'install_deps' >/dev/null 2>&1; rc=$?
chk "C8k apt-get install failure is still fatal" '[[ $rc -ne 0 ]]'

# --- finding 9: version skew warning
cat > "$W/side134" <<'S'
#!/bin/bash
echo "QEMU emulator version 9.1.0"
S
chmod +x "$W/side134"; fresh
o=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SIDE_BIN='$W/side134' QEMU_VER=10.2.2 WRAPPER_PATH='$T/kvm' VENDOR_PATH='$T/kvm.pve' LIST_FILE='$T/vms' PREFIX=/opt/qemu-ad; warn_version_skew" 2>&1); rc=$?
chk "C8l skew (installed 9.1.0, want 10.2.2): warning, rc 0" '[[ $rc -eq 0 && $o == *"warning"* && $o == *"9.1.0"* ]]'
cat > "$W/side134" <<'S'
#!/bin/bash
echo "QEMU emulator version 10.2.2"
S
o=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; SIDE_BIN='$W/side134' QEMU_VER=10.2.2; warn_version_skew" 2>&1)
chk "C8m no skew: silent" '[[ -z $o ]]'

# --- finding 11: del-vm
fresh; printf '200\n201\n202\n' > "$T/vms"; chmod 640 "$T/vms"
L 'del_vm 201' >/dev/null 2>&1; rc=$?
chk "C8n del-vm removes only that id" '[[ $rc -eq 0 ]] && [[ $(cat $T/vms | tr "\n" " ") == "200 202 " ]]'
chk "C8o del-vm preserves mode" '[[ $(stat -c %a $T/vms) == 640 ]]'
chk "C8p del-vm leaves no temp files next to the list" '[[ $(ls $T | grep -c "^vms\.") -eq 0 ]]'
fresh; printf '200\n' > "$T/vms"; L 'del_vm 200' >/dev/null 2>&1; rc=$?
chk "C8q del-vm of the last id: ok, empty list (grep exit 1 tolerated)" '[[ $rc -eq 0 && ! -s $T/vms ]]'
fresh; printf '200\n' > "$T/vms"
cat > "$W/stub/grep" <<'S'
#!/bin/bash
[[ $1 == -vx* ]] && exit 2; exec /bin/grep "$@"
S
chmod +x "$W/stub/grep"; L 'del_vm 200' >/dev/null 2>&1; rc=$?
chk "C8r grep hard error: fatal, list unchanged, no temp left" '[[ $rc -ne 0 && $(cat $T/vms) == 200 && $(ls $T | grep -c "^vms\.") -eq 0 ]]'
command rm -f "$W/stub/grep"

# --- finding 13: leading-zero VMIDs, quoted wrapper paths
fresh; L 'add_vm 0200' >/dev/null 2>&1; rc=$?
chk "C8s add-vm rejects leading-zero VMID" '[[ $rc -ne 0 ]] && ! grep -qx 0200 "$T/vms" 2>/dev/null'
fresh; L 'del_vm 0200' >/dev/null 2>&1; rc=$?   # list absent -> must still fail
chk "C8t del-vm rejects leading-zero VMID" '[[ $rc -ne 0 ]]'
fresh; L 'add_vm 200' >/dev/null 2>&1; rc=$?
chk "C8u add-vm 200 still works" '[[ $rc -eq 0 ]] && grep -qx 200 "$T/vms"'
# wrapper with a space and $ in paths must still be valid and route correctly
fresh; mkdir -p "$T/we ird"; cp "$W/real" "$T/we ird/re al"; cp "$W/side" "$T/we ird/si de"
PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; VENDOR_PATH='$T/we ird/re al' SIDE_BIN='$T/we ird/si de' LIST_FILE='$T/we ird/vm s' LOG_FILE='$T/we ird/log'; write_wrapper '$T/wr'" >/dev/null 2>&1
printf '200\n' > "$T/we ird/vm s"
chk "C8v wrapper with spaces in paths passes bash -n" 'bash -n "$T/wr"'
o=$(bash "$T/wr" -pidfile /var/run/qemu-server/200.pid); chk "C8w spaced paths: listed id -> side" '[[ $o == SIDE* ]]'
o=$(bash "$T/wr" -pidfile /var/run/qemu-server/201.pid); chk "C8x spaced paths: unlisted id -> vendor" '[[ $o == REAL* ]]'
fresh; mkdir -p "$T/d"; cp "$W/side" "$T/d/"'s$(touch PWNED)'
PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; VENDOR_PATH='$W/real' SIDE_BIN='$T/d/s\$(touch PWNED)' LIST_FILE='$T/vms' LOG_FILE='$T/log'; write_wrapper '$T/wr2'" >/dev/null 2>&1
printf '200\n' > "$T/vms"; ( cd "$T" && bash "$T/wr2" -pidfile /var/run/qemu-server/200.pid >"$T/wr2.out" 2>&1 )
chk "C8y metacharacters in SIDE_BIN are not executed; wrapper still reaches the side binary" '[[ ! -e $T/PWNED && $(cat $T/wr2.out) == SIDE* ]]'


echo "== C9 PR3: QA findings"
# --- 1. FULL `main install` end to end (stubs for apt/git/wget/tar/make/configure), rc must be 0
HAVE_USERNS=0; unshare -Ur true 2>/dev/null && HAVE_USERNS=1
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
exit 0
S
cat > "$W/stub/make" <<'S'
#!/bin/bash
if [[ ${1:-} == install ]]; then mkdir -p "$MAKE_PREFIX/bin"; printf '#!/bin/bash\necho "QEMU emulator version 9.9.9"\n' > "$MAKE_PREFIX/bin/qemu-system-x86_64"; chmod +x "$MAKE_PREFIX/bin/qemu-system-x86_64"; fi
exit 0
S
cat > "$W/stub/tar" <<'S'
#!/bin/bash
d=""; while [[ $# -gt 0 ]]; do [[ $1 == -C ]] && { d=$2; shift; }; shift; done
mkdir -p "$d/qemu-9.9.9"; printf '#!/bin/bash\nexit 0\n' > "$d/qemu-9.9.9/configure"; chmod +x "$d/qemu-9.9.9/configure"
S
cat > "$W/stub/git" <<'S'
#!/bin/bash
case "$1" in clone) d="${@: -1}"; mkdir -p "$d/.git"; printf 'p\n' > "$d/qemu-9.9.9.patch" ;; *) : ;; esac
S
chmod +x "$W/stub/"*
fullinstall() { # fullinstall <home-dir>; runs the REAL script as a subprocess, like an operator would
  local H=$1; command rm -rf "$H"; mkdir -p "$H/src" "$H/bin"; printf 'vendor\n' > "$H/bin/kvm"; chmod +x "$H/bin/kvm"
  : > "$H/calls"
  unshare -Ur env STATE="$H" MAKE_PREFIX="$H/opt" PATH="$W/stub:$PATH" QEMU_VER=9.9.9 QEMU_SHA256= PATCH_SHA256= PREFIX="$H/opt" SRC_ROOT="$H/src" \
     WRAPPER_PATH="$H/bin/kvm" VENDOR_PATH="$H/bin/kvm.pve" LIST_FILE="$H/vms" LOG_FILE="$H/log" DPKG_LOCK="$H/nolock" \
     bash "$SCRIPT" "${@:2}" >"$H/out" 2>&1; echo $?; }
if [[ $HAVE_USERNS -eq 1 ]]; then
  rc=$(fullinstall "$W/fi" install)
  chk "C9a FULL 'install' exits 0 (QA bug: 'staged: unbound variable' after success)" '[[ $rc -eq 0 ]]'
  chk "C9a no 'unbound variable' anywhere in install output" '! grep -q "unbound variable" "$W/fi/out"'
  chk "C9a install result: wrapper in place, vendor moved to kvm.pve, divert recorded, no staged leftover" 'grep -q "Generated by qemu-ad-pve" "$W/fi/bin/kvm" && grep -qx vendor "$W/fi/bin/kvm.pve" && [[ ! -e $W/fi/bin/kvm.qemu-ad-new ]] && grep -q -- "--divert" "$W/fi/calls"'
  rc=$(fullinstall "$W/fi2" install); rc2=$(unshare -Ur env STATE="$W/fi2" MAKE_PREFIX="$W/fi2/opt" PATH="$W/stub:$PATH" QEMU_VER=9.9.9 QEMU_SHA256= PATCH_SHA256= PREFIX="$W/fi2/opt" SRC_ROOT="$W/fi2/src" WRAPPER_PATH="$W/fi2/bin/kvm" VENDOR_PATH="$W/fi2/bin/kvm.pve" LIST_FILE="$W/fi2/vms" LOG_FILE="$W/fi2/log" DPKG_LOCK="$W/fi2/nolock" bash "$SCRIPT" install >/dev/null 2>&1; echo $?)
  chk "C9b second full 'install' (idempotent re-run) exits 0" '[[ $rc2 -eq 0 ]]'
  rc3=$(unshare -Ur env STATE="$W/fi2" PATH="$W/stub:$PATH" PREFIX="$W/fi2/opt" WRAPPER_PATH="$W/fi2/bin/kvm" VENDOR_PATH="$W/fi2/bin/kvm.pve" LIST_FILE="$W/fi2/vms" bash "$SCRIPT" uninstall >/dev/null 2>&1; echo $?)
  chk "C9c full 'uninstall' exits 0 and restores the vendor file at /usr/bin/kvm" '[[ $rc3 -eq 0 ]] && grep -qx vendor "$W/fi2/bin/kvm" && [[ ! -e $W/fi2/bin/kvm.pve ]]'
else note "C9a-c skipped: user namespaces unavailable (need EUID 0 for need_root)"; fi

# --- 2. argv[0] contract (needs a C compiler for an exec target that prints its own argv[0])
if command -v cc >/dev/null; then
  cat > "$W/p.c" <<'CEOF'
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
int main(int c,char**v){
  for(int i=1;i<c;i++){
    if(!strcmp(v[i],"--exit7"))return 7;
    if(!strcmp(v[i],"--cat")){int ch;while((ch=getchar())!=EOF)putchar(ch);return 0;}
    if(!strcmp(v[i],"--sleep")){printf("pid=%d\n",getpid());fflush(stdout);sleep(30);return 0;}
  }
  printf("ARGV0=%s\n",v[0]);for(int i=1;i<c;i++)printf("ARG=%s\n",v[i]);return 0;}
CEOF
  cc -o "$W/prog" "$W/p.c" 2>/dev/null && HAVEC=1 || HAVEC=0
else HAVEC=0; fi
if [[ $HAVEC -eq 1 ]]; then
  fresh; cp "$W/prog" "$T/real"; cp "$W/prog" "$T/side"
  PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; WRAPPER_PATH='/usr/bin/kvm' VENDOR_PATH='$T/real' SIDE_BIN='$T/side' LIST_FILE='$T/vms' LOG_FILE='$T/log'; write_wrapper '$T/wr'" >/dev/null 2>&1
  printf '200\n' > "$T/vms"
  o=$(bash "$T/wr" -pidfile /var/run/qemu-server/201.pid -x); chk "C9d UNLISTED guest: argv[0] is /usr/bin/kvm (qemu-server parse_cmdline needs kvm\$; QEMU needs it for default KVM accel)" '[[ $o == *"ARGV0=/usr/bin/kvm"* ]]'
  chk "C9d unlisted: argv after argv[0] untouched" '[[ $o == *"ARG=-pidfile"* && $o == *"ARG=-x"* ]]'
  o=$(bash "$T/wr" -id 200 -pidfile /var/run/qemu-server/200.pid); chk "C9e LISTED guest: argv[0] is /usr/bin/kvm and -id dropped" '[[ $o == *"ARGV0=/usr/bin/kvm"* && $o != *"ARG=-id"* && $o != *"ARG=200"* ]]'
  bash "$T/wr" -pidfile /var/run/qemu-server/201.pid --exit7 >/dev/null; rc=$?; chk "C9f exit code propagates (unlisted, 7)" '[[ $rc -eq 7 ]]'
  bash "$T/wr" -pidfile /var/run/qemu-server/200.pid --exit7 >/dev/null; rc=$?; chk "C9f exit code propagates (listed, 7)" '[[ $rc -eq 7 ]]'
  o=$(printf 'hello\nworld\n' | bash "$T/wr" -pidfile /var/run/qemu-server/201.pid --cat); chk "C9g stdin passes through (unlisted)" '[[ $o == $'"'"'hello\nworld'"'"' ]]'
  o=$(printf 'a\n' | bash "$T/wr" -pidfile /var/run/qemu-server/200.pid --cat); chk "C9g stdin passes through (listed)" '[[ $o == a ]]'
  bash "$T/wr" -pidfile /var/run/qemu-server/201.pid --sleep > "$T/sig.out" & bp=$!; sleep 1
  rp=$(sed -n 's/^pid=//p' "$T/sig.out"); chk "C9h wrapper EXECs the target (same pid, so signals/pidfile semantics are unchanged)" '[[ -n $rp && $rp == $bp ]]'
  kill -TERM "$bp" 2>/dev/null; wait "$bp" 2>/dev/null; rc=$?; chk "C9h SIGTERM reaches the target (rc 143)" '[[ $rc -eq 143 ]]'
else note "C9d-h skipped: no C compiler"; fi

# --- 3. list file format (documented): only a bare VMID on its own line matches
fresh; mkw
printf '# comment\n\n200\n' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid); chk "C9i bare VMID among comment/blank lines still routes to side" '[[ $o == SIDE* ]]'
printf '# 200\n' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid); chk "C9i '# 200' (commented out) does not match -> vendor" '[[ $o == REAL* ]]'
# N3: whitespace and CR around the VMID are tolerated (they used to fall back to vendor and were INFO)
for pair in '200 |trailing space' ' 200|leading space' ' 200 |leading+trailing space' '200\r|CR (CRLF line ending)' '200 \r|space then CR' '\t200\t|tabs'; do
  content=${pair%%|*}; label=${pair#*|}
  printf "$content\n" > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
  chk "C9j N3 list line with $label routes to SIDE" '[[ $o == SIDE* ]]'
done
printf '200\r\n201\r\n' > "$T/vms"
chk "C9j N3 CRLF file: 200 -> SIDE, 201 -> SIDE, 20 and 2000 -> REAL (no prefix/suffix match)" '[[ $(K -pidfile /var/run/qemu-server/200.pid) == SIDE* && $(K -pidfile /var/run/qemu-server/201.pid) == SIDE* && $(K -pidfile /var/run/qemu-server/20.pid) == REAL* && $(K -pidfile /var/run/qemu-server/2000.pid) == REAL* ]]'
printf '200' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid); chk "C9j N3 last line without newline matches" '[[ $o == SIDE* ]]'
printf '200 # note\n2000\n' > "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid)
chk "C9j trailing comment text still does NOT match (documented: bare VMID only) -> vendor, never a crash" '[[ $o == REAL* ]]'
if [[ $(id -u) -ne 0 ]]; then printf '200\n' > "$T/vms"; chmod 000 "$T/vms"; o=$(K -pidfile /var/run/qemu-server/200.pid 2>/dev/null); rc=$?; chmod 644 "$T/vms"
  chk "C9k unreadable list file: no crash, falls back to vendor" '[[ $rc -eq 0 && $o == REAL* ]]'
else note "C9k skipped: running as root, chmod 000 does not make the list unreadable"; fi

# --- 4. showcmd mirrors the wrapper (same function), incl. -id and +pve
fresh; cat > "$W/stub/qm" <<'S'
#!/bin/bash
[[ $1 == showcmd ]] || exit 0
printf '/usr/bin/kvm \\\n  -id 200 \\\n  -name "my vm+pve5" \\\n  -pidfile /var/run/qemu-server/200.pid \\\n  -machine '"'"'hpet=off,type=pc-q35-10.1+pve0'"'"'\n'
S
chmod +x "$W/stub/qm"
o=$(L 'printf "200\n" > "$LIST_FILE"; showcmd 200' 2>&1)
last=$(tail -1 <<<"$o")
chk "C9l showcmd (listed): side line has no -id" '[[ $last != *" -id "* ]]'
chk "C9l showcmd: +pve stripped inside -machine only; name keeps +pve5" '[[ $last == *"type=pc-q35-10.1"* && $last != *"pve0"* && $last == *"+pve5"* ]]'
chk "C9l showcmd: side line starts with the side binary" '[[ $last == "$W/side "* ]]'
o=$(L 'showcmd 201' 2>&1); chk "C9m showcmd (unlisted): states it runs on the vendor binary unchanged" '[[ $o == *"NOT listed"* ]]'
command rm -f "$W/stub/qm"

# --- 5. pre-flight checks
fresh; command rm -f "$T/kvm"; L 'install_wrapper' >/dev/null 2>"$W/pf.err"; rc=$?
chk "C9n /usr/bin/kvm missing: install dies clearly, no divert call, no vendor file" '[[ $rc -ne 0 && ! -e $T/kvm.pve ]] && ! grep -q -- --divert "$T/calls" && grep -q "does not exist" "$W/pf.err"'
if command -v python3 >/dev/null; then
  fresh; printf 'x' > "$W/lockf"
  python3 -c "
import fcntl,time,sys
f=open('$W/lockf','w'); fcntl.lockf(f, fcntl.LOCK_EX); print('held',flush=True); time.sleep(6)" > "$W/h.out" & hp=$!; sleep 1
  L "DPKG_LOCK='$W/lockf' install_wrapper" >/dev/null 2>"$W/pf2.err"; rc=$?
  chk "C9o fcntl lock held (like dpkg): install refuses, kvm intact, no divert" '[[ $rc -ne 0 ]] && grep -qx vendor "$T/kvm" && ! grep -q -- --divert "$T/calls" && grep -q "holds" "$W/pf2.err"'
  L "DPKG_LOCK='$W/lockf' install_wrapper" >/dev/null 2>&1 && flk=ok || flk=refused
  L 'install_wrapper' >/dev/null 2>&1; chk "C9o without the lock holder env the same install proceeds (control)" '[[ -f $T/kvm.pve ]]'
  wait $hp 2>/dev/null
  fresh; L 'install_wrapper' >/dev/null 2>&1
  python3 -c "
import fcntl,time
f=open('$W/lockf','w'); fcntl.lockf(f, fcntl.LOCK_EX); print('held',flush=True); time.sleep(5)" > "$W/h.out" & hp=$!; sleep 1
  L "DPKG_LOCK='$W/lockf' uninstall" >/dev/null 2>&1; rc=$?
  chk "C9p lock held: uninstall refuses, wrapper still in place" '[[ $rc -ne 0 ]] && grep -q "Generated by qemu-ad-pve" "$T/kvm" && [[ -e $T/kvm.pve ]]'
  wait $hp 2>/dev/null
  # flock(1) must NOT be used: dpkg uses fcntl locks, flock(1) cannot see them
  chk "C9q script does not call flock(1)" '! grep -E "(^|[^a-z_])flock( |$)" "$SCRIPT" | grep -v "^ *#" | grep -q .'
fi

# --- 6. no missing-kvm window: inotify watcher (falls back to poll) while install + uninstall run
if command -v inotifywait >/dev/null; then
  fresh; (inotifywait -q -m -e delete -e moved_from -e create -e moved_to "$T" --format '%e %f' > "$T/ino.log" 2>/dev/null) & ip=$!; sleep 0.3
  L 'install_wrapper' >/dev/null 2>&1; L 'uninstall' >/dev/null 2>&1; sleep 0.3; kill $ip 2>/dev/null
  # kvm may be replaced (MOVED_TO kvm) but must never be the source of a delete/move away without an immediate replacement: check no 'DELETE kvm' / 'MOVED_FROM kvm'
  chk "C9r inotify: /usr/bin/kvm is never deleted or moved away (only replaced atomically)" '! grep -E "^(DELETE|MOVED_FROM) kvm$" "$T/ino.log"'
else
  fresh; ( while :; do [[ -e $T/kvm ]] || { echo MISSING >> "$T/w.log"; }; done ) & wp=$!
  L 'install_wrapper' >/dev/null 2>&1; L 'uninstall' >/dev/null 2>&1; kill $wp 2>/dev/null
  chk "C9r busy-poll: /usr/bin/kvm never missing during install+uninstall (inotify-tools not installed)" '[[ ! -s $T/w.log ]]'
fi

# --- 7. purge also guards LIST_FILE
purge2() { fresh; PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }
   PREFIX=/opt/qemu-ad LIST_FILE='$1' WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" >/dev/null 2>&1; echo $?; }
for lf in / /etc /etc/passwd /usr/bin/kvm /root/.ssh/authorized_keys relative/vms /etc/qemu-ad/../passwd /etc/qemu-ad/ /home/x/vms \
  /usr/local/bin /usr/local/share /usr/local/lib /usr/local/vms /usr/local/qemu-ad/vms /opt/qemu-ad /opt/qad/vms /srv/qad/vms /srv/x \
  /etc/qemu-ad/. /etc/qemu-ad/./vms /var/lib/qemu-ad/. /var/lib/qemu-ad/./vms /etc/qemu-ad//vms /etc/qemu-ad/sub/.. /etc/qemu-ad/vms/ /etc/qemu-ad/vms/. /./etc/qemu-ad/vms /etc/qemu-ad /var/lib/qemu-ad; do
  r=$(purge2 "$lf"); chk "C10 purge rejects LIST_FILE='$lf' before any rm" '[[ $r -ne 0 && ! -s $T/rm.log ]]'
done
for lf in /etc/qemu-ad/vms /var/lib/qemu-ad/vms /etc/qemu-ad/lists/vms; do
  r=$(purge2 "$lf"); chk "C10 purge allows LIST_FILE='$lf' (removed with rm -f, not -rf)" '[[ $r -eq 0 && -s $T/rm.log ]] && grep -qx "RM -f $lf" "$T/rm.log" && ! grep -q "^RM -rf.* $lf" "$T/rm.log"'
done

# --- 10. N1 (more): directories refused; LIST_FILE removed with rm -f only; PREFIX non-canonical forms
if [[ $HAVE_USERNS -eq 1 ]] && unshare -Urm bash -c 'mount -t tmpfs none /etc' 2>/dev/null; then
  fresh
  r=$(unshare -Urm env PATH="$W/stub:$PATH" bash -c "mount -t tmpfs none /etc && mkdir -p /etc/qemu-ad/adir /etc/qemu-ad && source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }
     PREFIX=/opt/qemu-ad LIST_FILE=/etc/qemu-ad/adir WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" >/dev/null 2>&1; echo $?)
  chk "C10 purge refuses a LIST_FILE that is an existing directory (/etc/qemu-ad/adir)" '[[ $r -ne 0 && ! -s $T/rm.log ]]'
  fresh
  r=$(unshare -Urm env PATH="$W/stub:$PATH" bash -c "mount -t tmpfs none /etc && mkdir -p /etc/qemu-ad && : > /etc/qemu-ad/vms && source '$W/lib.sh'; set -euo pipefail; rm(){ echo \"RM \$*\" >> '$T/rm.log'; }
     PREFIX=/opt/qemu-ad LIST_FILE=/etc/qemu-ad/vms WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" >/dev/null 2>&1; echo $?)
  chk "C10 purge of an existing regular LIST_FILE works (control for the directory case)" '[[ $r -eq 0 ]] && grep -qx "RM -f /etc/qemu-ad/vms" "$T/rm.log"'
else note "C10 directory-refusal case skipped: cannot mount a tmpfs over /etc in a user namespace"; fi

# --- 8. add-vm rejects 0 / leading zeros
for v in 0 00 007 0200; do fresh; L "add_vm $v" >/dev/null 2>&1; rc=$?; chk "C11 add-vm rejects '$v'" '[[ $rc -ne 0 ]] && ! grep -qx "$v" "$T/vms" 2>/dev/null'; done

# --- 11. N3: one list-matching helper, used by wrapper, add-vm, del-vm, showcmd
fresh; printf '200\r\n' > "$T/vms"; L 'add_vm 200' >/dev/null 2>&1; rc=$?
chk "N3 add-vm on a CRLF list does not append a duplicate" '[[ $rc -eq 0 && $(wc -l < "$T/vms") -eq 1 ]]'
for c in '200 ' ' 200' '\t200 \r'; do
  fresh; printf "$c\n" > "$T/vms"; L 'add_vm 200' >/dev/null 2>&1
  chk "N3 add-vm: no duplicate for line '$c'" '[[ $(wc -l < "$T/vms") -eq 1 ]]'
done
fresh; printf '200\r\n201\r\n202\r\n' > "$T/vms"; L 'del_vm 201' >/dev/null 2>&1; rc=$?
chk "N3 del-vm removes the CRLF line for 201 and keeps the others byte-exact" '[[ $rc -eq 0 && $(od -An -c "$T/vms" | tr -d " \n") == "200\r\n202\r\n" ]]'
for c in '201 ' ' 201' '\t201\t'; do
  fresh; printf "200\n$c\n202\n" > "$T/vms"; L 'del_vm 201' >/dev/null 2>&1
  chk "N3 del-vm removes padded line '$c'" '[[ $(tr "\n" " " < "$T/vms") == "200 202 " ]]'
done
fresh; printf '2000\r\n20\r\n' > "$T/vms"; L 'del_vm 200' >/dev/null 2>&1
chk "N3 del-vm 200 does not touch 2000 / 20" '[[ $(tr -d "\r" < "$T/vms" | tr "\n" " ") == "2000 20 " ]]'
fresh; printf '200' > "$T/vms"; L 'add_vm 201' >/dev/null 2>&1
chk "N3 add-vm onto a list whose last line has no newline keeps both ids on their own lines" '[[ $(tr "\n" " " < "$T/vms") == "200 201 " ]]'
fresh; cat > "$W/stub/qm" <<'S'
#!/bin/bash
[[ $1 == showcmd ]] || exit 0
printf '/usr/bin/kvm \\\n  -id 200 \\\n  -pidfile /var/run/qemu-server/200.pid\n'
S
chmod +x "$W/stub/qm"
o=$(L 'printf "200\r\n" > "$LIST_FILE"; showcmd 200' 2>&1)
chk "N3 showcmd treats a CRLF list line as listed" '[[ $o == *"IS listed"* ]]'
o=$(L 'printf " 200 \n" > "$LIST_FILE"; showcmd 200' 2>&1)
chk "N3 showcmd treats a padded list line as listed" '[[ $o == *"IS listed"* ]]'
command rm -f "$W/stub/qm"
fresh; L 'write_wrapper "$WRAPPER_PATH"' >/dev/null
chk "N3 wrapper embeds the shared list-matching helper (no private grep -qx)" 'grep -q "^qad_list_has" "$T/kvm" && ! grep -q "grep -qx \"" "$T/kvm"'

# --- 12. N4: missing / unwritable log dir must not write anything to stderr and must not change routing/rc
mkw; printf '200\n' > "$T/vms"; sed -i "s#^log=.*#log=$T/nodir/sub/log#" "$T/kvm"
o=$(K -pidfile /var/run/qemu-server/200.pid 2>"$T/e1"); rc=$?
chk "N4 listed VM, log dir missing: stdout from side, rc 0" '[[ $o == SIDE* && $rc -eq 0 ]]'
chk "N4 listed VM, log dir missing: stderr is EMPTY" '[[ ! -s $T/e1 ]]'
o=$(K -pidfile /var/run/qemu-server/201.pid 2>"$T/e2"); chk "N4 unlisted VM: stderr empty, vendor" '[[ $o == REAL* && ! -s $T/e2 ]]'
mkdir -p "$T/ro"; chmod 555 "$T/ro"; sed -i "s#^log=.*#log=$T/ro/log#" "$T/kvm"
if [[ $(id -u) -ne 0 ]]; then
  o=$(K -pidfile /var/run/qemu-server/200.pid 2>"$T/e3"); rc=$?
  chk "N4 log dir not writable: still silent, still starts on side" '[[ $o == SIDE* && $rc -eq 0 && ! -s $T/e3 ]]'
fi
mkdir -p "$T/logdir"; sed -i "s#^log=.*#log=$T/logdir#" "$T/kvm"
o=$(K -pidfile /var/run/qemu-server/200.pid 2>"$T/e4"); rc=$?
chk "N4 log path is a directory: silent, still starts" '[[ $o == SIDE* && $rc -eq 0 && ! -s $T/e4 ]]'
mkdir -p "$T/okdir"; sed -i "s#^log=.*#log=$T/okdir/log#" "$T/kvm"
K -pidfile /var/run/qemu-server/200.pid >/dev/null 2>&1
chk "N4 control: with a writable log dir the line IS logged" 'grep -q "vmid=200 exec" "$T/okdir/log"'
# the wrapper must not fail even under bash -e/-u (qm may run it that way via a different shell option set)
o=$(bash -eu "$T/kvm" -pidfile /var/run/qemu-server/200.pid 2>&1); chk "N4 wrapper run under bash -eu with a good log is fine" '[[ $o == SIDE* ]]'

# --- 13. N5: recovery hint when pve-qemu-kvm was removed while the divert exists
fresh; L 'install_wrapper' >/dev/null 2>&1; command rm -f "$T/kvm.pve"   # what `apt remove pve-qemu-kvm` does
L 'uninstall' >/dev/null 2>"$W/n5.err"; rc=$?
chk "N5 uninstall with vendor binary gone: refuses (rc!=0), wrapper and divert untouched" '[[ $rc -ne 0 ]] && grep -q "Generated by qemu-ad-pve" "$T/kvm" && [[ -f $T/div ]]'
chk "N5 uninstall message tells how to recover (reinstall pve-qemu-kvm, then re-run uninstall)" 'grep -qi "reinstall" "$W/n5.err" && grep -q "pve-qemu-kvm" "$W/n5.err" && grep -q "uninstall" "$W/n5.err"'
L 'install_wrapper' >/dev/null 2>"$W/n5b.err"; rc=$?
chk "N5 re-running install in that state: refuses with the same recovery hint" '[[ $rc -ne 0 ]] && grep -qi "reinstall" "$W/n5b.err" && grep -q "pve-qemu-kvm" "$W/n5b.err"'
o=$(L 'status' 2>&1)
chk "N5 status warns when the divert exists but the vendor binary is missing" '[[ $o == *"WARNING"* && $o == *"reinstall"* ]]'
printf 'vendor-reinstalled\n' > "$T/kvm.pve"   # apt install pve-qemu-kvm: dpkg writes the diverted path
L 'uninstall' >/dev/null 2>&1; rc=$?
chk "N5 after reinstalling the package, uninstall succeeds and restores the vendor binary" '[[ $rc -eq 0 ]] && grep -qx vendor-reinstalled "$T/kvm"'
fresh; L 'install_wrapper' >/dev/null 2>&1; o=$(L 'status' 2>&1)
chk "N5 status: no warning in the healthy state" '[[ $o != *"WARNING"* ]]'

# --- 14. N2: stale header comments / usage()
chk "N2 header no longer says hidden=1 clears the hypervisor bit" '! sed -n 1,70p "$SCRIPT" | grep -qi "hypervisor bit clear" && sed -n 1,70p "$SCRIPT" | grep -q "kvm=off"'
chk "N2 header no longer says +pve is stripped from each argument" '! sed -n 1,70p "$SCRIPT" | grep -qi "from each argument" && sed -n 1,70p "$SCRIPT" | grep -qi -- "-machine"'
u=$(bash "$SCRIPT" help 2>&1)
m=0; for k in $(sed -n 's/^\([A-Z][A-Z0-9_]*\)="\${\1:-.*/\1/p' "$SCRIPT") DPKG_LOCK; do [[ $u == *"$k"* ]] || { echo "usage() lacks $k"; m=1; }; done
chk "N2 usage() lists every env knob the script reads (derived from the script, plus DPKG_LOCK)" '[[ $m -eq 0 ]]'
chk "N2 usage() documents DPKG_LOCK" '[[ $u == *DPKG_LOCK* ]]'
chk "N2 usage() / header no longer claim CRLF falls back to vendor" '! grep -qi "silently fall back" "$(dirname "$SCRIPT")/README.md"'

# --- 9. docs: list format and overrides documented
chk "C12a README documents the list file format" 'grep -qi "one .*VMID per line" "$(dirname "$SCRIPT")/README.md" && grep -qi "CRLF" "$(dirname "$SCRIPT")/README.md"'
chk "C12b README Overrides list covers every env knob (incl. DPKG_LOCK)" 'm=0; for k in QEMU_VER PREFIX SRC_ROOT FORCE_REBUILD PATCH_REPO TARBALL_URL LIST_FILE WRAPPER_PATH VENDOR_PATH LOG_FILE QEMU_SHA256 PATCH_SHA256 DPKG_LOCK; do grep -q "\`$k\`" "$(dirname "$SCRIPT")/README.md" || { echo "missing $k"; m=1; }; done; [[ $m -eq 0 ]]'
chk "C12c README no longer claims hidden=1 clears the hypervisor bit" '! grep -qi "clears the hypervisor bit" "$(dirname "$SCRIPT")/README.md"'
chk "C12d README no longer lists CRLF / padded lines as a known limitation" '! grep -qi "silently fall back to the vendor binary" "$(dirname "$SCRIPT")/README.md" && grep -qi "CRLF" "$(dirname "$SCRIPT")/README.md"'
chk "C12e README has the apt-remove recovery hint" 'grep -qi "reinstall" "$(dirname "$SCRIPT")/README.md" && grep -qi "pve-qemu-kvm" "$(dirname "$SCRIPT")/README.md" && grep -qi "was removed\|already removed\|already ran" "$(dirname "$SCRIPT")/README.md"'

# ===========================================================================
echo "== C15 PR5: crypto backend (BUG-A), version-skew warnings (BUG-B), list pattern fork (LOW 1), purge hint (LOW 2)"
# --- BUG-A: gcrypt in deps and configure; existing builds without it get rebuilt
cat > "$W/stub/apt-get" <<'S'
#!/bin/bash
echo "apt-get $*" >> "${STATE:-/tmp}/apt.log"; exit 0
S
cat > "$W/stub/ldd" <<'S'
#!/bin/bash
# LDD_MODE=gcrypt|nocrypt
echo "$*" >> "${STATE:-/tmp}/ldd.log"
echo "	libglib-2.0.so.0 => /lib/libglib-2.0.so.0 (0x1)"
[[ ${LDD_MODE:-nocrypt} == gcrypt ]] && echo "	libgcrypt.so.20 => /lib/libgcrypt.so.20 (0x2)"
exit 0
S
cat > "$W/stub/make" <<'S'
#!/bin/bash
echo "make $*" >> "${STATE:-/tmp}/make.log"
if [[ $1 == install ]]; then
  p=$(cat "$STATE/cfg.prefix"); mkdir -p "$p/bin"
  printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$p/bin/qemu-system-x86_64"; chmod +x "$p/bin/qemu-system-x86_64"
fi
exit 0
S
chmod +x "$W/stub/apt-get" "$W/stub/ldd" "$W/stub/make"
fresh; : > "$T/apt.log"; L 'install_deps' >/dev/null 2>&1
chk "C15a apt build deps include libgcrypt20-dev" 'grep -q "libgcrypt20-dev" "$T/apt.log"'
# BQ <env...>: run build_qemu against a fake source tree + prefix in $T. cfg.args = what configure got.
mkbq() { fresh; mkdir -p "$T/src" "$T/prefix/bin"
  cat > "$T/src/configure" <<'S'
#!/bin/bash
echo "$*" > "$STATE/cfg.args"; for a in "$@"; do [[ $a == --prefix=* ]] && echo "${a#--prefix=}" > "$STATE/cfg.prefix"; done; exit 0
S
  chmod +x "$T/src/configure"; : > "$T/make.log"; }
BQ() { env "$@" PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; PREFIX='$T/prefix' SIDE_BIN='$T/prefix/bin/qemu-system-x86_64' SRC_DIR='$T/src'; build_qemu" >"$T/bq.out" 2>&1; }
mkbq; BQ STATE="$T"; rc=$?
chk "C15b no side binary: configure gets --enable-gcrypt and --disable-gnutls" '[[ $rc -eq 0 ]] && grep -q -- "--enable-gcrypt" "$T/cfg.args" && grep -q -- "--disable-gnutls" "$T/cfg.args"'
chk "C15c a successful build leaves a build stamp under PREFIX recording the gcrypt flag" 'grep -rq -- "--enable-gcrypt" "$T/prefix" --include=".*" 2>/dev/null || grep -rq -- "--enable-gcrypt" "$T/prefix"'
# existing side binary, no stamp (installed by an older version of this script)
mkbq; printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$T/prefix/bin/qemu-system-x86_64"; chmod +x "$T/prefix/bin/qemu-system-x86_64"
BQ STATE="$T" LDD_MODE=nocrypt; rc=$?
chk "C15d existing build without libgcrypt (ldd) and no stamp: rebuilt automatically with gcrypt" '[[ $rc -eq 0 ]] && grep -q -- "--enable-gcrypt" "$T/cfg.args" && grep -q "^make install" "$T/make.log"'
chk "C15d2 the rebuild tells the user why" 'grep -qi "gcrypt" "$T/bq.out" && grep -qi "rebuil" "$T/bq.out"'
mkbq; printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$T/prefix/bin/qemu-system-x86_64"; chmod +x "$T/prefix/bin/qemu-system-x86_64"
BQ STATE="$T" LDD_MODE=gcrypt; rc=$?
chk "C15e existing build already linked to libgcrypt, no stamp: NOT rebuilt" '[[ $rc -eq 0 && ! -e $T/cfg.args && ! -s $T/make.log ]]'
# second run after a build is a no-op (stamp matches)
mkbq; BQ STATE="$T" LDD_MODE=nocrypt; rm -f "$T/cfg.args"; : > "$T/make.log"; BQ STATE="$T" LDD_MODE=nocrypt; rc=$?
chk "C15f install again after a stamped build: no rebuild (idempotent)" '[[ $rc -eq 0 && ! -e $T/cfg.args && ! -s $T/make.log ]]'
# stamp present but with different flags -> rebuild
mkbq; BQ STATE="$T" LDD_MODE=gcrypt; stamp=$(grep -rl -- "--enable-gcrypt" "$T/prefix" | head -1); rm -f "$T/cfg.args"
[[ -n $stamp ]] && echo "--enable-libiscsi" > "$stamp"; BQ STATE="$T" LDD_MODE=gcrypt; rc=$?
chk "C15g stamp with different configure flags: rebuilt" '[[ $rc -eq 0 && -e $T/cfg.args ]]'
mkbq; printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$T/prefix/bin/qemu-system-x86_64"; chmod +x "$T/prefix/bin/qemu-system-x86_64"
BQ STATE="$T" LDD_MODE=gcrypt FORCE_REBUILD=1; rc=$?
chk "C15h FORCE_REBUILD=1 still forces a rebuild" '[[ $rc -eq 0 && -e $T/cfg.args ]]'
fresh; mkdir -p "$T/prefix/bin"; printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$T/prefix/bin/qemu-system-x86_64"; chmod +x "$T/prefix/bin/qemu-system-x86_64"
o=$(STATE="$T" LDD_MODE=nocrypt L "PREFIX='$T/prefix' SIDE_BIN='$T/prefix/bin/qemu-system-x86_64'; status" 2>&1)
chk "C15i status warns when the side binary has no crypto backend (VGA/VNC guests will not start)" '[[ $o == *WARNING* && $o == *gcrypt* ]]'
o=$(STATE="$T" LDD_MODE=gcrypt L "PREFIX='$T/prefix' SIDE_BIN='$T/prefix/bin/qemu-system-x86_64'; status" 2>&1)
chk "C15j status: no crypto warning when libgcrypt is linked" '[[ $o != *"no crypto"* && $o != *"FORCE_REBUILD"* ]]'

# --- BUG-B: showcmd warnings for listed guests
sk() { # sk <vmid> <list-content> <qm-showcmd-body...>; prints showcmd output (stdout+stderr)
  local id=$1 lst=$2; shift 2; fresh; printf '%b' "$lst" > "$T/vms"
  { printf '#!/bin/bash\n[[ $1 == showcmd ]] || exit 0\ncat <<"EOQ"\n'; printf '%s\n' "$@"; printf 'EOQ\n'; } > "$W/stub/qm"; chmod +x "$W/stub/qm"
  L "QEMU_VER=10.2.2; SIDE_BIN='$W/side102'; showcmd $id" 2>&1; }
printf '#!/bin/bash\necho "QEMU emulator version 10.2.2"\n' > "$W/side102"; chmod +x "$W/side102"
base=('/usr/bin/kvm \' '  -id 200 \' '  -pidfile /var/run/qemu-server/200.pid \')
o=$(sk 200 '200\n' "${base[@]}" '  -name vm' ); chk "C16a clean listed guest: no skew WARNING" '[[ $o != *WARNING* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -spice tls-port=61000,addr=localhost' ); chk "C16b listed + -spice: WARNING mentioning spice" '[[ $o == *WARNING*[Ss]pice* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -machine type=pc-q35-11.0+pve0,accel=kvm' ); chk "C16c listed + pc-q35-11.0 (side 10.2.2): WARNING mentioning the machine" '[[ $o == *WARNING*pc-q35-11.0* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -machine type=pc-i440fx-10.3,accel=kvm' ); chk "C16d listed + pc-i440fx-10.3 (newer minor): WARNING" '[[ $o == *WARNING*pc-i440fx-10.3* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -machine type=pc-q35-10.1+pve0,accel=kvm' ); chk "C16e listed + pc-q35-10.1 (older): no WARNING" '[[ $o != *WARNING* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -machine type=pc-q35-10.2,accel=kvm' ); chk "C16e2 listed + pc-q35-10.2 (same as side): no WARNING" '[[ $o != *WARNING* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -machine type=pc-q35-9.2+pve1' ); chk "C16e3 listed + pc-q35-9.2 (older major): no WARNING" '[[ $o != *WARNING* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -loadstate /dev/pve/vm-200-state-s1' ); chk "C16f listed + -loadstate: WARNING mentioning loadstate" '[[ $o == *WARNING*loadstate* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -drive file=rbd:pool/vm-200-disk-0:conf=/etc/ceph/ceph.conf,if=none,id=drive-scsi0' ); chk "C16g listed + rbd: drive: WARNING mentioning rbd" '[[ $o == *WARNING*rbd* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -drive file=pbs:repo=x,if=none,id=d0' ); chk "C16h listed + pbs: drive: WARNING mentioning pbs" '[[ $o == *WARNING*pbs* ]]'
o=$(sk 201 '200\n' '/usr/bin/kvm \' '  -id 201 \' '  -pidfile /var/run/qemu-server/201.pid \' '  -spice x -loadstate y -machine pc-q35-11.0' ); chk "C16i UNLISTED guest with all skew options: no WARNING (it runs on the vendor binary)" '[[ $o != *WARNING* && $o == *"NOT listed"* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -name spice-lab \' '  -smbios type=1,product=pc-q35-11.0-x,serial=rbd:y' ); chk "C16j option values that merely contain the words are not flagged (-name spice-lab, smbios text)" '[[ $o != *WARNING* ]]'
o=$(sk 200 '200\n' "${base[@]}" '  -spice a \' '  -loadstate b' ); chk "C16k several problems: one WARNING per problem" '[[ $(grep -c "^WARNING" <<<"$o") -ge 2 ]]'
command rm -f "$W/stub/qm"

# --- LOW 1: qad_list_has must not fork a subshell for the pattern
fresh; printf '200\n' > "$T/vms"
r=$(L "eval \"_orig_\$(declare -f qad_list_pat)\"; qad_list_pat() { echo \$BASHPID >> '$T/pids'; _orig_qad_list_pat \"\$@\"; }; : > '$T/pids'; me=\$BASHPID; qad_list_has 200 '$T/vms'; echo rc=\$? me=\$me; cat '$T/pids'" 2>&1)
chk "C17a qad_list_has still matches (rc 0)" '[[ $r == *"rc=0"* ]]'
chk "C17b qad_list_has builds the pattern in the current shell (no \$(...) subshell fork)" 'me=$(sed -n "s/.*me=//p" <<<"$r"); ! grep -v -x -- "$me" <<<"$(sed "1,/^rc=/d" <<<"$r")" | grep -q .'
chk "C17c qad_list_has body has no command substitution" '! L "declare -f qad_list_has" | grep -q "[$](" '
chk "C17d qad_list_has: unlisted / missing file still rc 1" '[[ $(L "qad_list_has 201 \"$T/vms\" && echo y || echo n") == n && $(L "qad_list_has 200 \"$T/none\" && echo y || echo n") == n ]]'

# --- LOW 2: purge refusal of LIST_FILE tells how to proceed
fresh; e=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ :; }; PREFIX=/opt/qemu-ad LIST_FILE=/root/my-vms WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" 2>&1 >/dev/null); rc=$?
chk "C18a purge with LIST_FILE outside the allow-list: refused" '[[ $rc -ne 0 && $e == *"refusing to purge LIST_FILE=/root/my-vms"* ]]'
chk "C18b ...and the message says to run plain uninstall and delete the file by hand" '[[ $e == *"plain"* && $e == *uninstall* && $e == *"by hand"* ]]'
e=$(PATH="$W/stub:$PATH" bash -c "source '$W/lib.sh'; set -euo pipefail; rm(){ :; }; PREFIX=/opt/qemu-ad LIST_FILE=/etc/qemu-ad/../x WRAPPER_PATH='$T/n1' VENDOR_PATH='$T/n2'; uninstall --purge" 2>&1 >/dev/null)
chk "C18c non-canonical LIST_FILE refusal carries the same hint" '[[ $e == *"by hand"* ]]'

# --- README
R="$(dirname "$SCRIPT")/README.md"
chk "C19a README has a 'Vendor vs side version skew' section" 'grep -q "^## Vendor vs side version skew" "$R"'
chk "C19b skew table covers spice/qxl, pc-q35-11.0, rbd/pbs, CPU models, -loadstate, -id, +pveN, -iscsi, argv[0]" 'sec=$(sed -n "/^## Vendor vs side version skew/,/^## [^V]/p" "$R"); m=0; for k in "-spice" "qxl" "pc-q35-11.0" "rbd" "pbs" "-loadstate" "-id" "+pve" "-iscsi" "argv"; do grep -qF -- "$k" <<<"$sec" || { echo "missing $k"; m=1; }; done; grep -q "^| *Option" <<<"$sec" && [[ $m -eq 0 ]]'
chk "C19c README mentions the crypto backend / libgcrypt and the automatic rebuild" 'grep -qi "libgcrypt" "$R" && grep -qi "rebuil" "$R"'
chk "C19d README mentions showcmd WARNING lines" 'grep -q "WARNING" "$R"'

echo; echo "TIER1 RESULT: pass=$pass fail=$fail info=$info  (script: $SCRIPT)"
[[ $fail -eq 0 ]]
