#!/bin/bash
# qemu-ad-breakglass.sh - standalone, idempotent back-out of what qemu-ad-pve.sh installs.
#
# Use it when `qemu-ad-pve.sh uninstall` cannot be used (the script or its repo is gone, the divert
# is half-applied, pve-qemu-kvm was removed while diverted, ...). It does not need qemu-ad-pve.sh.
#
# DRY-RUN IS THE DEFAULT. Nothing is changed, created or written (no log file, no pre-state) unless you
# pass --apply. A dry run only reads the system and prints what an --apply run would do.
#
# What --apply does (every step is a no-op if already done):
#   1. Optional: destroys the VMs listed in QAD_BREAKGLASS_VMIDS (empty by default: no `qm destroy` unless set).
#      Needs QAD_PROTECTED_VMIDS (space-separated VMIDs, or the word `none`); refuses on any overlap.
#   2. Restores the real kvm binary: removes qemu-ad-pve's dpkg divert and puts the vendor file (VENDOR_PATH)
#      back over the wrapper (WRAPPER_PATH). If the vendor file is missing it reinstalls pve-qemu-kvm via apt;
#      as a last resort it symlinks WRAPPER_PATH to the packaged qemu-system-x86_64 next to it.
#      A divert that is not ours is left alone.
#   3. Only if step 2 left a real kvm binary: removes the VMID list, the wrapper log, the side-QEMU prefix and
#      the build tree (use --keep-build to keep the prefix and sources).
#   4. Verifies the end state and prints a PASS/FAIL report. Exit 0 only if everything passes.
# It never reboots, never touches a VM that is not in QAD_BREAKGLASS_VMIDS, never touches PCI devices, and
# refuses to write to a block device.
#
# Usage: qemu-ad-breakglass.sh [--apply] [--keep-build] [--capture-prestate [--force-prestate]] [--verify]
#   (no option)         dry run: print the plan and the CURRENT state report; change nothing; exit 0
#   --apply             actually make the changes (root required)
#   --dry-run           same as the default; refused together with --apply
#   --keep-build        keep PREFIX and the sources under SRC_ROOT
#   --capture-prestate  write a read-only snapshot of VM status/config and package/divert state to
#                       $STATE_DIR/pre-state, then exit (needs --apply to write; refuses to overwrite an
#                       existing one unless --force-prestate). If it exists, the verifier compares the
#                       protected VMs' status and PIDs with it.
#   --verify            only run the end-state report (read-only); exit 1 if any check fails
#   -h, --help          this text
#
# Environment (same names and defaults as qemu-ad-pve.sh):
#   PREFIX (/opt/qemu-ad)  SRC_ROOT (/opt/src)  QEMU_VER (10.2.2)  LIST_FILE (/etc/qemu-ad/vms)
#   WRAPPER_PATH (/usr/bin/kvm)  VENDOR_PATH (/usr/bin/kvm.pve)  LOG_FILE (/var/log/qemu-ad-wrapper.log)
#   DPKG_LOCK (/var/lib/dpkg/lock-frontend)  PVE_QEMU_CONF_DIR (/etc/pve/qemu-server)
# Break-glass only:
#   QAD_BREAKGLASS_VMIDS     VMIDs to destroy (default: none). Digits only, space separated.
#   QAD_PROTECTED_VMIDS      VMIDs that must never be touched, or `none`. Required when QAD_BREAKGLASS_VMIDS is set.
#   QAD_BREAKGLASS_STATE_DIR run log, saved VM configs, pre-state (default /var/lib/qemu-ad-breakglass).
#   QAD_PID_DIR              where qemu-server keeps <vmid>.pid (default /var/run/qemu-server).
#   QAD_BREAKGLASS_POLL_SECS seconds between the 30 checks that a stopped VM is really down (default 2).
#   QAD_BREAKGLASS_SANDBOX   test hook: an absolute directory. Allows --apply without root, but then EVERY path
#                            above must lie inside it. Use it for rehearsals only, never on a real host.
#
# The same allow-lists as `qemu-ad-pve.sh uninstall --purge` apply (outside a sandbox): PREFIX is a canonical
# directory below /opt, /srv or /usr/local (not a standard /usr/local subdirectory); LIST_FILE is a file below
# /etc/qemu-ad or /var/lib/qemu-ad.
#
# Not undone: apt build dependencies (harmless) and VMs' own configs (qm config lines such as
# `cpu:`/`args:` that you set for the patch). Pre-state files may contain VM configs: the directory is mode 700.
set -u
export LC_ALL=C

PREFIX="${PREFIX:-/opt/qemu-ad}"
SRC_ROOT="${SRC_ROOT:-/opt/src}"
QEMU_VER="${QEMU_VER:-10.2.2}"
LIST_FILE="${LIST_FILE:-/etc/qemu-ad/vms}"
WRAPPER_PATH="${WRAPPER_PATH:-/usr/bin/kvm}"
VENDOR_PATH="${VENDOR_PATH:-/usr/bin/kvm.pve}"
LOG_FILE="${LOG_FILE:-/var/log/qemu-ad-wrapper.log}"
DPKG_LOCK="${DPKG_LOCK:-/var/lib/dpkg/lock-frontend}"
PVE_QEMU_CONF_DIR="${PVE_QEMU_CONF_DIR:-/etc/pve/qemu-server}"
VMIDS="${QAD_BREAKGLASS_VMIDS:-}"
PROTECTED="${QAD_PROTECTED_VMIDS:-}"
STATE_DIR="${QAD_BREAKGLASS_STATE_DIR:-/var/lib/qemu-ad-breakglass}"
PID_DIR="${QAD_PID_DIR:-/var/run/qemu-server}"
SANDBOX="${QAD_BREAKGLASS_SANDBOX:-}"
POLL="${QAD_BREAKGLASS_POLL_SECS:-2}"
[[ $POLL =~ ^[0-9]+$ ]] || { printf 'error: QAD_BREAKGLASS_POLL_SECS must be a whole number\n' >&2; exit 2; }
MARK='Generated by qemu-ad-pve'
PRE="$STATE_DIR/pre-state"
RUNLOG="$STATE_DIR/breakglass.log"

die() { printf 'error: %s\n' "$*" >&2; exit 2; }
usage() { sed -n '2,/^set -u$/p' "$0" | sed '$d' | sed 's/^# \{0,1\}//'; }

APPLY=0; DRYFLAG=0; KEEP_BUILD=0; CAPTURE=0; FORCE_PRE=0; VERIFY_ONLY=0
for a in "$@"; do
  case "$a" in
    --apply) APPLY=1 ;;
    --dry-run|-n) DRYFLAG=1 ;;
    --keep-build) KEEP_BUILD=1 ;;
    --capture-prestate) CAPTURE=1 ;;
    --force-prestate) FORCE_PRE=1 ;;
    --verify) VERIFY_ONLY=1 ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown option: %s\n' "$a" >&2; exit 2 ;;
  esac
done
((APPLY && DRYFLAG)) && die "--apply and --dry-run are mutually exclusive"
DRY=$((1 - APPLY))
((VERIFY_ONLY && APPLY)) && die "--verify is read-only; do not combine it with --apply"

# ---------------------------------------------------------------- validation (before anything is touched)
canon() {  # canon <label> <path>: absolute, no "..", no "//", no trailing "/", no "." component
  case "$2" in
    /*) ;;
    *) die "refusing: $1=$2 is not an absolute path" ;;
  esac
  case "$2" in
    *..*|*//*|*/|*/./*|*/.|*[[:space:]]*) die "refusing: $1=$2 is not a canonical path (no spaces, '..', '//', trailing '/', '.' components)" ;;
  esac
}
for kv in "PREFIX=$PREFIX" "SRC_ROOT=$SRC_ROOT" "LIST_FILE=$LIST_FILE" "WRAPPER_PATH=$WRAPPER_PATH" "VENDOR_PATH=$VENDOR_PATH" \
          "LOG_FILE=$LOG_FILE" "DPKG_LOCK=$DPKG_LOCK" "STATE_DIR=$STATE_DIR" "PID_DIR=$PID_DIR" "PVE_QEMU_CONF_DIR=$PVE_QEMU_CONF_DIR"; do
  canon "${kv%%=*}" "${kv#*=}"
done
[[ $QEMU_VER =~ ^[0-9][0-9A-Za-z._-]*$ ]] || die "refusing: QEMU_VER=$QEMU_VER has unexpected characters"
[[ $WRAPPER_PATH != "$VENDOR_PATH" ]] || die "refusing: WRAPPER_PATH and VENDOR_PATH are the same path"

if [[ -n $SANDBOX ]]; then
  canon QAD_BREAKGLASS_SANDBOX "$SANDBOX"
  [[ $SANDBOX != / && -d $SANDBOX ]] || die "refusing: QAD_BREAKGLASS_SANDBOX=$SANDBOX must be an existing directory other than /"
  for kv in "PREFIX=$PREFIX" "SRC_ROOT=$SRC_ROOT" "LIST_FILE=$LIST_FILE" "WRAPPER_PATH=$WRAPPER_PATH" "VENDOR_PATH=$VENDOR_PATH" \
            "LOG_FILE=$LOG_FILE" "DPKG_LOCK=$DPKG_LOCK" "STATE_DIR=$STATE_DIR" "PID_DIR=$PID_DIR" "PVE_QEMU_CONF_DIR=$PVE_QEMU_CONF_DIR"; do
    case "${kv#*=}" in "$SANDBOX"/?*) ;; *) die "refusing: ${kv%%=*}=${kv#*=} is outside QAD_BREAKGLASS_SANDBOX=$SANDBOX" ;; esac
  done
else
  case "$PREFIX" in
    /usr/local/bin|/usr/local/sbin|/usr/local/lib|/usr/local/lib64|/usr/local/etc|/usr/local/share|/usr/local/include|/usr/local/src|/usr/local/man|/usr/local/games)
      die "refusing: PREFIX=$PREFIX is a system directory" ;;
    /opt/?*|/usr/local/?*|/srv/?*) ;;
    *) die "refusing: PREFIX=$PREFIX must be a directory below /opt, /usr/local or /srv" ;;
  esac
  case "$LIST_FILE" in
    /etc/qemu-ad/?*|/var/lib/qemu-ad/?*) ;;
    *) die "refusing: LIST_FILE=$LIST_FILE must be a file below /etc/qemu-ad or /var/lib/qemu-ad" ;;
  esac
  case "$SRC_ROOT" in /|/usr|/usr/*|/etc|/etc/*|/bin|/sbin|/lib*|/boot|/boot/*|/dev|/dev/*|/proc|/proc/*|/sys|/sys/*|/root|/home) die "refusing: SRC_ROOT=$SRC_ROOT is a system directory" ;; esac
fi
[[ ! -d $LIST_FILE ]] || die "refusing: LIST_FILE=$LIST_FILE is a directory"

# Never write to a block device: check every path we may create, rewrite, move onto or delete, and where it resolves.
blockdev_check() {
  local p r
  for p in "$WRAPPER_PATH" "$VENDOR_PATH" "${WRAPPER_PATH}.qemu-ad-new" "${WRAPPER_PATH}.bg-new" "$LIST_FILE" "$LOG_FILE" "$STATE_DIR" \
           "$RUNLOG" "$PRE" "$PREFIX" "$SRC_ROOT"; do
    r=$(readlink -f -- "$p" 2>/dev/null) || r=$p
    if [[ -b $p || -b $r ]]; then die "refusing: $p is (or resolves to) a block device"; fi
  done
}
blockdev_check

# VMID lists
for v in $VMIDS; do [[ $v =~ ^[0-9]+$ ]] || die "refusing: QAD_BREAKGLASS_VMIDS entry '$v' is not a number"; done
VMIDS=$(for v in $VMIDS; do echo $((10#$v)); done | sort -un | tr '\n' ' '); VMIDS=${VMIDS% }
if [[ -n ${PROTECTED//[[:space:]]/} ]]; then
  if [[ ${PROTECTED//[[:space:]]/} == none ]]; then PROTECTED=""; else
    for v in $PROTECTED; do [[ $v =~ ^[0-9]+$ ]] || die "refusing: QAD_PROTECTED_VMIDS entry '$v' is not a number (numbers or 'none')"; done
    PROTECTED=$(for v in $PROTECTED; do echo $((10#$v)); done | sort -un | tr '\n' ' '); PROTECTED=${PROTECTED% }
  fi
  PROT_SET=1
else
  PROT_SET=0
fi
if [[ -n $VMIDS ]]; then
  ((PROT_SET)) || die "refusing: QAD_BREAKGLASS_VMIDS is set but QAD_PROTECTED_VMIDS is not; list the VMIDs to protect, or say 'none' explicitly"
  for v in $VMIDS; do
    for p in $PROTECTED; do [[ $v == "$p" ]] && die "refusing: VMID $v is in both QAD_BREAKGLASS_VMIDS and QAD_PROTECTED_VMIDS"; done
  done
fi

if ((APPLY)) && [[ -z $SANDBOX ]]; then
  [[ ${EUID:-$(id -u)} -eq 0 ]] || die "--apply needs root"
fi

# ---------------------------------------------------------------- logging / acting
LOG_READY=0
log() {
  local m; m="$(date '+%F %T') $*"
  printf '%s\n' "$m"
  ((LOG_READY)) && printf '%s\n' "$m" >> "$RUNLOG" 2>/dev/null
  return 0
}
if ((APPLY && !VERIFY_ONLY)); then
  if (umask 077; mkdir -p "$STATE_DIR") 2>/dev/null && : >> "$RUNLOG" 2>/dev/null; then chmod 600 "$RUNLOG" 2>/dev/null; LOG_READY=1; else
    printf 'warning: cannot write %s; continuing without a run log\n' "$RUNLOG" >&2
  fi
fi
# act <cmd...>: run it with --apply, otherwise only say what would run
act() {
  if ((DRY)); then log "DRY-RUN: $*"; return 0; fi
  log "+ $*"; "$@"
}
have() { command -v "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------- probes (read-only)
is_elf() { [[ $(head -c4 -- "$1" 2>/dev/null | od -An -tx1 | tr -d ' \n') == 7f454c46 ]]; }
is_wrapper_file() { [[ -f $1 ]] && grep -q -- "$MARK" "$1" 2>/dev/null; }
exists_or_link() { [[ -e $1 || -L $1 ]]; }
divert_list() { have dpkg-divert && dpkg-divert --list "$WRAPPER_PATH" 2>/dev/null; }
divert_ours() { local l; l=$(divert_list) || return 1; [[ $l == *" to ${VENDOR_PATH}"* ]]; }
divert_any()  { local l; l=$(divert_list) || return 1; [[ -n $l ]]; }
dpkg_lock_held() {
  local f="$1" ino
  [[ -e $f ]] || return 1
  ino=$(stat -c %i "$f") || return 1
  [[ -r /proc/locks ]] || return 1
  awk -v ino="$ino" '{ n = split($6, a, ":"); if (a[n] == ino) found = 1 } END { exit !found }' /proc/locks
}
vendor_resolves() {  # WRAPPER_PATH exists, resolves to a real ELF, and is not our wrapper
  [[ -e $WRAPPER_PATH ]] || return 1
  local r; r=$(readlink -f -- "$WRAPPER_PATH") || return 1
  is_elf "$r" && ! is_wrapper_file "$r"
}
vm_status() { qm status "$1" 2>/dev/null | awk '{print $2}'; }
vm_exists() { have qm && qm config "$1" >/dev/null 2>&1; }

# ---------------------------------------------------------------- pre-state capture
capture_prestate() {
  if [[ -d $PRE && $FORCE_PRE -eq 0 ]]; then log "pre-state already exists at $PRE (not overwriting; use --force-prestate)"; return 0; fi
  if ((DRY)); then log "DRY-RUN: would capture pre-state (qm list/config, package, divert, pid and directory info) into $PRE"; return 0; fi
  ( umask 077; mkdir -p "$PRE" ) || { log "cannot create $PRE"; return 1; }
  (
    umask 077
    { date -Is; hostname; } > "$PRE/captured-at.txt" 2>&1
    if have qm; then qm list > "$PRE/qm-list.txt" 2>&1; else echo "qm not found" > "$PRE/qm-list.txt"; fi
    local f id
    for f in "$PVE_QEMU_CONF_DIR"/*.conf; do
      [[ -e $f ]] || continue; id=$(basename "$f" .conf)
      have qm && qm config "$id" > "$PRE/qm-config-$id.txt" 2>&1
    done
    have dpkg && dpkg -l pve-qemu-kvm qemu-server pve-manager > "$PRE/dpkg-l.txt" 2>&1
    ls -l "$WRAPPER_PATH" "$VENDOR_PATH" > "$PRE/ls-kvm.txt" 2>&1
    sha256sum "$(readlink -f -- "$WRAPPER_PATH")" > "$PRE/sha256-kvm.txt" 2>&1
    divert_list > "$PRE/divert-kvm.txt" 2>&1
    have dpkg && dpkg -S "$WRAPPER_PATH" > "$PRE/dpkg-S-kvm.txt" 2>&1
    have pveversion && pveversion -v > "$PRE/pveversion.txt" 2>&1
    : > "$PRE/pids.txt"
    for f in "$PID_DIR"/*.pid; do [[ -e $f ]] && echo "$(basename "$f" .pid) $(cat "$f")" >> "$PRE/pids.txt"; done
    ls -la "$(dirname "$LIST_FILE")" "$PREFIX" "$SRC_ROOT" > "$PRE/qemu-ad-dirs.txt" 2>&1
  )
  log "pre-state captured in $PRE"
}

# ---------------------------------------------------------------- step 1: optional VM destruction
step_vms() {
  local id st
  if [[ -z $VMIDS ]]; then log "--- step 1: no VMs to destroy (QAD_BREAKGLASS_VMIDS is empty)"; return 0; fi
  log "--- step 1: destroy VM(s) $VMIDS only (protected: ${PROTECTED:-none})"
  for id in $VMIDS; do
    for p in $PROTECTED; do [[ $id == "$p" ]] && { log "BUG: $id is protected"; return 1; }; done
    # drop it from the list first, so a later failure cannot leave it routed to the side binary
    if [[ -f $LIST_FILE ]] && grep -qxE "[[:space:]]*${id}[[:space:]]*" "$LIST_FILE"; then
      if ((DRY)); then log "DRY-RUN: remove $id from $LIST_FILE"; else
        local t; t=$(mktemp "${LIST_FILE}.XXXXXX") || return 1
        grep -vxE "[[:space:]]*${id}[[:space:]]*" "$LIST_FILE" > "$t"; cat "$t" > "$LIST_FILE"; rm -f "$t"; log "removed $id from $LIST_FILE"
      fi
    else log "$id not in $LIST_FILE"; fi
    if ! vm_exists "$id"; then log "VM $id does not exist: nothing to do"; continue; fi
    if ((!DRY)); then
      ( umask 077; mkdir -p "$STATE_DIR/saved" && qm config "$id" > "$STATE_DIR/saved/${id}-config-$(date +%s).txt" 2>&1 ) || { log "cannot save the config of VM $id; not destroying it"; return 1; }
    else log "DRY-RUN: save the config of VM $id under $STATE_DIR/saved"; fi
    st=$(vm_status "$id")
    if [[ $st == running ]]; then
      act qm stop "$id" --skiplock 1 --timeout 45
      if ((!DRY)); then
        for _ in $(seq 1 30); do [[ $(vm_status "$id") == running ]] || break; sleep "$POLL"; done
        [[ $(vm_status "$id") == running ]] && { log "ERROR: VM $id is still running; not destroying it"; return 1; }
      fi
    fi
    if qm config "$id" 2>/dev/null | grep -q '^protection: 1'; then act qm set "$id" --protection 0 --skiplock 1; fi
    act qm destroy "$id" --purge 1 --destroy-unreferenced-disks 1 --skiplock 1
  done
}

# ---------------------------------------------------------------- step 2: restore the vendor kvm
KVM_OK=1
step_kvm() {
  local f
  log "--- step 2: restore the real $WRAPPER_PATH"
  if ((!DRY)) && dpkg_lock_held "$DPKG_LOCK"; then
    log "ERROR: another package manager holds $DPKG_LOCK; wait for it to finish and run again"; KVM_OK=0; return 1
  fi
  for f in "${WRAPPER_PATH}.qemu-ad-new" "${WRAPPER_PATH}.bg-new"; do exists_or_link "$f" && act rm -f "$f"; done
  if divert_ours; then
    if ! exists_or_link "$VENDOR_PATH"; then
      log "divert recorded but $VENDOR_PATH is missing: reinstalling pve-qemu-kvm (dpkg puts the vendor file at $VENDOR_PATH)"
      have apt-get && act env DEBIAN_FRONTEND=noninteractive apt-get install --reinstall -y -o Dpkg::Options::=--force-confold pve-qemu-kvm
    fi
    if ((DRY)) || exists_or_link "$VENDOR_PATH"; then
      # drop the divert record first (no file moves), then ONE atomic mv puts the vendor file back over the wrapper
      if act dpkg-divert --local --no-rename --remove "$WRAPPER_PATH"; then
        act mv -f "$VENDOR_PATH" "$WRAPPER_PATH" || { log "ERROR: could not move $VENDOR_PATH onto $WRAPPER_PATH"; KVM_OK=0; }
      else log "ERROR: dpkg-divert --remove failed; nothing moved"; KVM_OK=0; return 1; fi
    else
      log "ERROR: $VENDOR_PATH is still missing; dropping the divert record and falling back to repair"
      act dpkg-divert --local --no-rename --remove "$WRAPPER_PATH"
    fi
  elif divert_any; then
    log "WARNING: a divert for $WRAPPER_PATH exists that is not ours; leaving it alone:"; divert_list | sed 's/^/    /'
  fi
  # no divert (or already removed): is the wrapper path a vendor binary?
  if ((!DRY)) && ! vendor_resolves; then
    log "$WRAPPER_PATH is not a vendor ELF (half-installed, or the wrapper was left behind): repairing"
    if exists_or_link "$VENDOR_PATH" && is_elf "$(readlink -f -- "$VENDOR_PATH")" && ! is_wrapper_file "$(readlink -f -- "$VENDOR_PATH")" && ! divert_any; then
      act mv -f "$VENDOR_PATH" "$WRAPPER_PATH"
    fi
    if ! vendor_resolves && have apt-get && ! divert_any; then
      act env DEBIAN_FRONTEND=noninteractive apt-get install --reinstall -y -o Dpkg::Options::=--force-confold pve-qemu-kvm
    fi
    local pk; pk="$(dirname "$WRAPPER_PATH")/qemu-system-x86_64"
    if ! vendor_resolves && ! divert_any && [[ -f $pk ]] && is_elf "$pk" && ! is_wrapper_file "$pk"; then
      log "last resort: symlink $WRAPPER_PATH -> qemu-system-x86_64 (the packaged layout)"
      ln -sfn qemu-system-x86_64 "${WRAPPER_PATH}.bg-new" && mv -fT "${WRAPPER_PATH}.bg-new" "$WRAPPER_PATH"
    fi
    vendor_resolves || { log "ERROR: $WRAPPER_PATH is still not a vendor binary"; KVM_OK=0; }
  elif ((DRY)) && ! vendor_resolves; then
    log "DRY-RUN: $WRAPPER_PATH is not a vendor ELF now; a real run would repair it (vendor file back in place, else apt --reinstall pve-qemu-kvm, else symlink)"
  fi
  # a stale vendor copy with no divert
  if ! divert_any && exists_or_link "$VENDOR_PATH" && vendor_resolves; then
    if [[ -L $VENDOR_PATH && $(readlink -f -- "$VENDOR_PATH") == "$(readlink -f -- "$WRAPPER_PATH")" ]] || cmp -s "$VENDOR_PATH" "$WRAPPER_PATH"; then
      act rm -f "$VENDOR_PATH"
    else
      log "WARNING: $VENDOR_PATH exists but differs from $WRAPPER_PATH; leaving it (inspect by hand)"
    fi
  fi
  return 0
}

# ---------------------------------------------------------------- step 3: remove qemu-ad artifacts
step_files() {
  log "--- step 3: remove qemu-ad files"
  local f it
  if ((!DRY && !KVM_OK)); then log "skipped: $WRAPPER_PATH is not a vendor binary yet, so the side QEMU is left in place"; return 0; fi
  if [[ -e $LIST_FILE || -L $LIST_FILE ]]; then act rm -f "$LIST_FILE"; fi
  if [[ -d $(dirname "$LIST_FILE") ]] && ! ((DRY)); then rmdir "$(dirname "$LIST_FILE")" 2>/dev/null; fi
  for f in "$LOG_FILE" "$LOG_FILE".[0-9]*; do [[ -e $f || -L $f ]] && act rm -f "$f"; done
  if ((KEEP_BUILD)); then log "keep-build: leaving $PREFIX and $SRC_ROOT"; return 0; fi
  if [[ -L $PREFIX ]]; then act rm -f "$PREFIX"; elif [[ -d $PREFIX ]]; then act rm -rf -- "$PREFIX"; fi
  for it in "qemu-${QEMU_VER}" "qemu-${QEMU_VER}.tar.xz" "qemu-${QEMU_VER}.tar.xz.part" "qemu-anti-detection" .extract.*; do
    if [[ -e $SRC_ROOT/$it || -L $SRC_ROOT/$it ]]; then act rm -rf -- "${SRC_ROOT:?}/${it:?}"; fi
  done
  if [[ -d $SRC_ROOT ]] && ! ((DRY)); then rmdir "$SRC_ROOT" 2>/dev/null; fi
  log "note: apt build dependencies (build-essential, libaio-dev, ...) are left installed; they are harmless"
}

# ---------------------------------------------------------------- step 4: verify
FAILS=0
chk() {  # chk <label> <cmd...>
  local l=$1; shift
  if "$@"; then log "  PASS  $l"; else log "  FAIL  $l"; FAILS=$((FAILS+1)); fi
}
t_no_divert() { ! divert_any; }
t_kvm_runs() { [[ -x $WRAPPER_PATH ]] && "$WRAPPER_PATH" --version >/dev/null 2>&1; }
t_dpkg_owns() { ! have dpkg || dpkg -S "$WRAPPER_PATH" 2>/dev/null | grep -q '^pve-qemu-kvm'; }
t_no_leftovers() { local f; for f in "$VENDOR_PATH" "${WRAPPER_PATH}.qemu-ad-new" "${WRAPPER_PATH}.bg-new"; do exists_or_link "$f" && return 1; done; return 0; }
t_absent() { [[ ! -e $1 && ! -L $1 ]]; }
t_no_log() { local f; for f in "$LOG_FILE" "$LOG_FILE".[0-9]*; do [[ -e $f ]] && return 1; done; return 0; }
t_no_tree() { local it; for it in "qemu-${QEMU_VER}" "qemu-${QEMU_VER}.tar.xz" "qemu-anti-detection"; do exists_or_link "$SRC_ROOT/$it" && return 1; done; return 0; }
t_vm_gone() { ! vm_exists "$1"; }
t_dpkg_audit() { ! have dpkg || [[ -z $(dpkg --audit 2>&1) ]]; }
t_same_status() {
  local id was cur bad=0
  for id in $PROTECTED; do
    was=$(awk -v i="$id" '$1==i{print $3}' "$PRE/qm-list.txt" 2>/dev/null)
    cur=$(qm list 2>/dev/null | awk -v i="$id" '$1==i{print $3}')
    [[ $was == "$cur" ]] || { bad=1; log "        VM $id status: pre-state=${was:-absent} now=${cur:-absent}"; }
  done
  ((bad == 0))
}
t_same_pids() {
  local id was cur bad=0
  for id in $PROTECTED; do
    was=$(awk -v i="$id" '$1==i{print $2}' "$PRE/pids.txt" 2>/dev/null)
    cur=$(cat "$PID_DIR/$id.pid" 2>/dev/null)
    [[ $was == "$cur" ]] || { bad=1; log "        VM $id pid: pre-state=${was:-none} now=${cur:-none}"; }
  done
  ((bad == 0))
}
step_verify() {
  FAILS=0
  log "--- step 4: end-state report$( ((DRY)) && ((!VERIFY_ONLY)) && echo ' (DRY-RUN: this is the CURRENT state, not the end state)')"
  chk "$WRAPPER_PATH is a vendor ELF (not the wrapper)" vendor_resolves
  chk "dpkg owns the kvm binary (pve-qemu-kvm), when dpkg is available" t_dpkg_owns
  chk "no dpkg divert for $WRAPPER_PATH" t_no_divert
  chk "no $VENDOR_PATH or staged-wrapper leftovers" t_no_leftovers
  chk "vendor kvm runs (--version)" t_kvm_runs
  chk "no VMID list ($LIST_FILE)" t_absent "$LIST_FILE"
  if ((KEEP_BUILD)); then log "  (keep-build: $PREFIX and the sources are not checked)"; else
    chk "no side QEMU prefix ($PREFIX)" t_absent "$PREFIX"
    chk "no build tree under $SRC_ROOT" t_no_tree
  fi
  chk "no wrapper log ($LOG_FILE)" t_no_log
  local v; for v in $VMIDS; do chk "VM $v gone" t_vm_gone "$v"; done
  chk "dpkg --audit is clean (when dpkg is available)" t_dpkg_audit
  if [[ -d $PRE && -n $PROTECTED ]]; then
    chk "protected VMs have the same status as in the pre-state" t_same_status
    chk "protected VMs have the same PIDs as in the pre-state (processes untouched)" t_same_pids
  else
    log "  INFO  no pre-state at $PRE (or no protected VMIDs): protected-VM comparison skipped"
  fi
  if ((FAILS)); then log "RESULT: FAIL ($FAILS check(s) failed)"; else log "RESULT: PASS"; fi
  ((FAILS == 0))
}

# ---------------------------------------------------------------- main
if ((VERIFY_ONLY)); then step_verify; exit $?; fi
if ((CAPTURE)); then capture_prestate; exit $?; fi
log "=== qemu-ad break glass start ($( ((DRY)) && echo 'DRY-RUN: pass --apply to make changes' || echo APPLY)) keep-build=$KEEP_BUILD ==="
rc=0
step_vms || rc=1
if ((rc && !DRY)); then log "step 1 failed; stopping before touching the kvm wrapper"; step_verify; exit 1; fi
step_kvm || rc=1
step_files || rc=1
if step_verify; then vrc=0; else vrc=1; fi
if ((DRY)); then log "dry run finished: nothing was changed. Re-run with --apply to do it."; exit $rc; fi
exit $((rc || vrc))
