#!/usr/bin/env bash
# Generated by tools/gen-launch.py from qm-showcmd-9200-raw.txt. Do not edit by hand; regenerate.
#
# Applied (see docs/roadmap.md): Intel vIOMMU (kernel-irqchip=split, intel-iommu intremap+caching-mode),
# both GPU functions behind pcie-root-port -> pcie-pci-bridge, large 64-bit MMIO aperture.
# Host impact: none by itself. Running this starts one QEMU process like `qm start` would, with the
# VM's existing disks/NICs; the VM config under /etc/pve is not modified. Do not run it while `qm`
# has the VM running. Remove this file to remove everything.
set -euo pipefail
QEMU_BIN=${QEMU_BIN:-/usr/bin/kvm}
exec -a /usr/bin/kvm "$QEMU_BIN" \
  -id 9200 \
  -name viommu-l1-gpu \
  -no-shutdown \
  -chardev socket,id=qmp,path=/var/run/qemu-server/9200.qmp,server=on,wait=off \
  -mon chardev=qmp,mode=control \
  -chardev socket,id=qmp-event,path=/var/run/qmeventd.sock,reconnect-ms=5000 \
  -mon chardev=qmp-event,mode=control \
  -pidfile /var/run/qemu-server/9200.pid \
  -daemonize \
  -smbios type=1,uuid=b62acca0-5306-4246-a72c-ca7d7cf12c94 \
  -object '{"id":"throttle-drive-efidisk0","limits":{},"qom-type":"throttle-group"}' \
  -blockdev '{"driver":"raw","file":{"driver":"file","filename":"/usr/share/pve-edk2-firmware//OVMF_CODE_4M.secboot.fd"},"node-name":"pflash0","read-only":true}' \
  -blockdev '{"detect-zeroes":"on","discard":"ignore","driver":"throttle","file":{"cache":{"direct":false,"no-flush":false},"detect-zeroes":"on","discard":"ignore","driver":"qcow2","file":{"aio":"io_uring","cache":{"direct":false,"no-flush":false},"detect-zeroes":"on","discard":"ignore","driver":"file","filename":"/mnt/fast_storage/images/9200/vm-9200-disk-0.qcow2","node-name":"ee1b291dff3bbd47e852bf9a80614bc","read-only":false},"node-name":"fe1b291dff3bbd47e852bf9a80614bc","read-only":false},"node-name":"drive-efidisk0","read-only":false,"throttle-group":"throttle-drive-efidisk0"}' \
  -smp 8,sockets=1,cores=8,maxcpus=8 \
  -nodefaults \
  -boot menu=on,strict=on,reboot-timeout=1000,splash=/usr/share/qemu-server/bootsplash.jpg \
  -vnc unix:/var/run/qemu-server/9200.vnc,password=on \
  -cpu host,+kvm_pv_eoi,+kvm_pv_unhalt \
  -m 12288 \
  -object '{"id":"throttle-drive-ide2","limits":{},"qom-type":"throttle-group"}' \
  -object '{"id":"throttle-drive-scsi0","limits":{},"qom-type":"throttle-group"}' \
  -object '{"id":"throttle-drive-scsi1","limits":{},"qom-type":"throttle-group"}' \
  -global ICH9-LPC.disable_s3=1 \
  -global ICH9-LPC.disable_s4=1 \
  -readconfig /usr/share/qemu-server/pve-q35-4.0.cfg \
  -device intel-iommu,intremap=on,caching-mode=on \
  -device vmgenid,guid=1940248a-8687-496f-a37b-ce0f1298b50e \
  -device usb-tablet,id=tablet,bus=ehci.0,port=1 \
  -device pcie-pci-bridge,id=gpubr,bus=ich9-pcie-port-1,addr=0x0 \
  -device vfio-pci,host=0000:02:00.0,id=hostpci0.0,bus=gpubr,addr=0x1.0,multifunction=on \
  -device vfio-pci,host=0000:02:00.1,id=hostpci0.1,bus=gpubr,addr=0x1.1 \
  -chardev socket,id=serial0,path=/var/run/qemu-server/9200.serial0,server=on,wait=off \
  -device isa-serial,chardev=serial0 \
  -device VGA,id=vga,bus=pcie.0,addr=0x1 \
  -iscsi initiator-name=iqn.1993-08.org.debian:01:3ddee23a4af0 \
  -blockdev '{"driver":"throttle","file":{"cache":{"direct":false,"no-flush":false},"driver":"qcow2","file":{"aio":"io_uring","cache":{"direct":false,"no-flush":false},"driver":"file","filename":"/mnt/fast_storage/images/9200/vm-9200-cloudinit.qcow2","node-name":"e835b7afb33bcc8acd866ac0b1afe2c","read-only":true},"node-name":"f835b7afb33bcc8acd866ac0b1afe2c","read-only":true},"node-name":"drive-ide2","read-only":true,"throttle-group":"throttle-drive-ide2"}' \
  -device ide-cd,bus=ide.1,unit=0,drive=drive-ide2,id=ide2 \
  -device virtio-scsi-pci,id=virtioscsi0,bus=pci.3,addr=0x1 \
  -blockdev '{"detect-zeroes":"unmap","discard":"unmap","driver":"throttle","file":{"cache":{"direct":true,"no-flush":false},"detect-zeroes":"unmap","discard":"unmap","driver":"qcow2","file":{"aio":"io_uring","cache":{"direct":true,"no-flush":false},"detect-zeroes":"unmap","discard":"unmap","driver":"file","filename":"/mnt/fast_storage/images/9200/vm-9200-disk-1.qcow2","node-name":"e4041cf368c32a8b727d8bef2e957b1","read-only":false},"node-name":"f4041cf368c32a8b727d8bef2e957b1","read-only":false},"node-name":"drive-scsi0","read-only":false,"throttle-group":"throttle-drive-scsi0"}' \
  -device scsi-hd,bus=virtioscsi0.0,channel=0,scsi-id=0,lun=0,drive=drive-scsi0,id=scsi0,device_id=drive-scsi0,bootindex=100,write-cache=on \
  -device virtio-scsi-pci,id=virtioscsi1,bus=pci.3,addr=0x2 \
  -blockdev '{"detect-zeroes":"unmap","discard":"unmap","driver":"throttle","file":{"cache":{"direct":true,"no-flush":false},"detect-zeroes":"unmap","discard":"unmap","driver":"qcow2","file":{"aio":"io_uring","cache":{"direct":true,"no-flush":false},"detect-zeroes":"unmap","discard":"unmap","driver":"file","filename":"/mnt/fast_storage/images/9200/vm-9200-disk-2.qcow2","node-name":"e08404f10dc49f2a82242ce311429cf","read-only":false},"node-name":"f08404f10dc49f2a82242ce311429cf","read-only":false},"node-name":"drive-scsi1","read-only":false,"throttle-group":"throttle-drive-scsi1"}' \
  -device scsi-hd,bus=virtioscsi1.0,channel=0,scsi-id=0,lun=1,drive=drive-scsi1,id=scsi1,device_id=drive-scsi1,write-cache=on \
  -netdev type=tap,id=net0,ifname=tap9200i0,script=/usr/libexec/qemu-server/pve-bridge,downscript=/usr/libexec/qemu-server/pve-bridgedown,vhost=on \
  -device virtio-net-pci,mac=BC:24:11:0E:69:36,netdev=net0,bus=pci.0,addr=0x12,id=net0,rx_queue_size=1024,tx_queue_size=256,host_mtu=1500 \
  -machine pflash0=pflash0,pflash1=drive-efidisk0,hpet=off,type=q35+pve0,kernel-irqchip=split \
  -fw_cfg name=opt/ovmf/X-PciMmio64Mb,string=65536
